alliance-genome/agr_ui

webpack.config.babel.js
This basically sends the hostname of the api server to the api server for the request rather then localhost.
=> Fixes AGR-546

src/containers/wordpress/style.css
@kevinschaper , @paaatrick  --- There were duplicate code blocks in wordpress/style.css file messing the display of post-specific pages.
=> Got rid of duplicate code blocks

src/components/collapsiblePanel.js, src/components/externalLink.js, src/components/orthology/index.js, src/components/orthology/orthologyUserGuide.js, src/containers/genePage/index.js
Hi there,
The pull requests adds a collapsible user guide in the orthology section above the orthology table. (AGR-415 https://agr-jira.atlassian.net/browse/AGR-415)
By default it looks like:
Toggling the header to expand and collapse the user guide section as needed:
Two components are added to the `./src/components`: 
- CollapsiblePanel replicates the basic feature react-bootstrap Panel, but is compatible with Bootstrap 4 css.
- ExternalLink for formatting non-AGR links
Thanks!
=> Agr 415 orthology user guide

src/components/orthology/index.js, src/components/orthology/orthologyBasicInfo.js, src/components/orthology/pantherCrossRef.js, src/containers/genePage/index.js
Hi there,
This PR adds the focus gene symbol to the orthology section.
`<OrthologyBasicInfo>` now replaces `<PantherCrossRef>` in the `genePage/index.js`. It creates an attribute list that includes both focus gene and panther link.
Thanks,
Sibyl
=> Agr 415 add focus gene

package.json, src/components/attribute/attributeLabel.js, src/components/attribute/attributeList.js, src/components/attribute/attributeValue.js, src/components/collapsibleList.js, src/components/collapsiblePanel.js, src/components/externalLink.js, src/components/orthology/orthologyBasicInfo.js, src/components/orthology/pantherCrossRef.js, src/components/primaryAttributesList.js, src/containers/diseasePage/basicDiseaseInfo.js, src/containers/layout/navLink.js, src/containers/layout/navLinksContainer.js, src/containers/search/filterSelector/singleFilterSelector.js, src/containers/search/search.js
I removed all uses of the deprecated React.PropTypes and also fixed a typo in one of the Class.propTypes definitions.  This should address the source of some of the warnings that @oblodgett  found during the UI build process.
=> AGR-591 - Removed deprecated React.PropTypes usage

package.json
https://github.com/react-ga/react-ga/issues/165
=> react-ga broken at v2.3.1, pin to v2.2.0 until issue is resolved.

src/components/externalLink.js, src/components/style.css, src/containers/genePage/dataSourceCard.js
Also applies the icon using CSS instead of as a separate element to avoid possibly having a line break between the link text and the icon.
=> AGR-624 Reformat source card to avoid IDs going outside of box

src/containers/layout/navLinksContainer.js
This takes care of the navigation issue detected when trying to access wordpress pages from the News pages by clicking on either the main menu or the sitemap menu.
Tested as followed: Assuming docker is installed 
1) Clone the agr_ui repos 
2) cd to agr_ui and checkout this branch (AGR-642)
3) Clean docker:  all exited, dangling docker containers 
List of all exited containers - cmd: docker ps -aq -f status=exited
Remove stopped containers - cmd: docker ps -aq --no-trunc | xargs docker rm
Remove dangling  images - cmd: docker images -q --filter dangling=true | xargs docker rmi 
4) Run : make docker-build-nginx
5) Run : make docker-run
6) Test that you can access Wordpress pages after you browse the news pages
=> Wordpress path: Changed main navigation  links from router Links to external links

.eslintrc, package.json, src/containers/layout/test.js, src/containers/search/tests/test.js, src/containers/wordpress/wordpressFeeds/test.js, src/reducers/tests/diseaseReducer.test.js, src/selectors/tests/searchSelectors.test.js
This change will make `eslint` run before `npm test` (or on-demand via `npm run lint`). Therefore, `eslint` will run in TravisCI so that we get feedback on that automatically as part of pull requests. These changes also clean up existing linter errors.
=> Pretest linting

src/constants.js, src/containers/wordpress/index.js
@paaatrick , added the orthology and the new disease tutorial pages to WP_PAGES map in constants.js - This should fix the current broken links on prod. Will investigate the long term solution later on.
=> Short term Fix for AGR-735

src/actions/disease.js, src/containers/diseasePage/diseasePageAssociationsTable.js
This fixes some bugs I found while doing more testing of the recent disease components refactor on dev. The gist is that the redux store should always hold the sorting field name that the react-bootstrap-table is expecting. We should only translate that to the name that the API is expecting at the very last minute (i.e. before we fire off the fetch request) and that doesn't go in the redux store.
=> Don't store API-translated field name when sorting

src/reducers/searchParsers.js
tiny change, down in the index go_synonyms was changed to synonyms a while ago.
=> AGR-800 fixed go synonym column

src/index.js
A separate chunk containing the polyfill is created (maybe something like dist/1.22909c9eb4b6a7a401b5.js, about ~88K) and is loaded iff the browser is missing certain features that we care about
=> lazy loading of polyfill based browser features

src/components/disease/evidenceCodesCell.js, src/components/disease/genePageDiseaseTable.js, src/containers/diseasePage/diseasePageAssociationsTable.js
This connects the evidence code column to a formatter. Also creates a shared component to display evidence codes in both disease tables.
=> Fix display of evidence codes on gene page

src/components/orthology/orthologyFilteredTable.js
Negative margin was causing the 'Method' label and the message when all orthologs were filtered to be hidden by the filter controls box.
=> Remove top margin from orthology table

package.json, src/components/dataPage/pageNav.js, src/components/dataPage/style.scss, src/components/style.scss, src/components/subsection.js, src/public/index.html
More testing indicated that using the vanilla bootstrap scrollspy implementation wasn't always reliable. I think it might have been due to a timing issue around when the bootstrap scrollspy was initialized vs when the subsection components were mounted. Regardless, I'm finding that using this react-specific package is more reliable.
=> Use react-scrollspy instead of vanilla bootstrap scrollspy

src/lib/searchHelpers.js, src/reducers/searchParsers.js
Facet values no longer use the same 'pretty' naming function as fields, fixing odd spaces in acronyms
=> Fix funky acronym spacing

src/components/headMetaTags.js
From:  https://www.w3.org/TR/2014/REC-json-ld-20140116/#node-identifiers
Should have been using `@id`, seems to work now:
=> Fix google structured data identifier

src/components/dataTable/loadingOverlay.js, src/components/dataTable/remoteDataTable.js, src/components/dataTable/style.scss
Some of the expression data might be slow enough to load to warrant indicating to the user that the table is loading. It seemed to make sense to add it to all the remote data tables, so I'm making this separate PR for it. I tried to set it up so it's not really noticeable when the loading happens quickly enough.
=> Add loading overlay to remote tables

src/components/dataTable/CellTooltip.js, src/components/dataTable/index.js, src/components/interaction/MITerm.js, src/components/interaction/genePhysicalInteractionDetailTable.js, src/containers/genePage/index.js
- fixes problems caused by null/undefined in crossReferences and detectionMethods
- take precaution before destruction objects by assigining default values {}
- tooltip for MITerm
- resolving geneA from either geneA or geneB
=> various interaction fixes

src/components/interaction/genePhysicalInteractionDetailTable.js
Sorry, I forgot about this feature request in my previous PR. 
They want the default sorting order for interaction table to be based on the interactor gene's symbol.
=> sorting by interactor name

src/containers/genePage/genomeFeatureWrapper.js
This was causing the genome viewer to have the wrong margins around it
=> Remove extraneous bootstrap row

src/components/orthology/orthologyBasicInfo.js, src/containers/genePage/index.js
With the API refactoring changes, this component was throwing an error when there was no Panther cross reference, which is (I think) expected for rat and human genes.
Slightly unrelated, I'm taking this opportunity to take out the "Focus gene" attribute. I think that was just a relic from when the sticky navigation panel wasn't there, and it's not a pattern that's used by other sections that utilize orthology. So I think it's safe to remove it.
=> Fix unavailable gene tree link

src/actions/genes.js, src/components/expression/expressionComparisonRibbon.js, src/components/orthology/constants.js, src/components/orthology/index.js, src/components/orthology/orthologyFilteredTable.js, src/components/orthology/orthologyTable.js, src/components/orthology/stringencySelection.js, src/components/orthology/utils.js, src/containers/genePage/index.js, src/lib/utils.js, src/reducers/geneReducer.js, src/selectors/geneSelectors.js
AGR-1132 @paaatrick the orthology and expression section should be fixed now. Though you might want doublecheck the expression section, as I haven't done too much testing with it.
One catch though, the orthology stringency filter is still determined on the client side, because the API response is missing the stringencyLevel in many entries. It's related to the ticket https://agr-jira.atlassian.net/browse/AGR-1373 Once that's fixed, I will file a separate PR to use that value.
=> AGR-1132 refactor orthology and expression for index refactoring

Dockerfile.build, src/containers/downloadsPage/index.js
PIs decided they don't want this publicly visible. I'm leaving the submission system-related infrastructure in place because I assume we'll need it at some point.
=> AGR-1429 Remove ingest files from download page

webpack.config-test.js
This issue was blocking the Ribbon PR since the beginning of the week.
Mocha should not be testing SASS files as we don't currently have a real strategy yet to test styling features.
Please merge the Ribbon PR after merging this one and the tests should now pass.
=> Stop mocha from testing sass files (MERGE first, then https://github.com/alliance-genome/agr_ui/pull/384)

src/components/interaction/genePhysicalInteractionDetailTable.js, src/lib/fetchData.js
To fix the client-side timeout of interactions table, I bumped the timeout limit up. I also trigger the error display instead the misleading fallback to "No Data", when an error occurs.
=> AGR-1543 (hotfix to release branch) fetching interactions

src/components/disease/diseaseComparisonRibbon.js
Something that I noticed before. The setState does not always merge correctly when we have a substructure that looks like the one already present, hence this brut force update to setState on the first summary level, since the subsequent merge does not replace items in the array.
Anyhow, we'll move away from setState possibly in profit of REACT hooks.
=> Fix AGR-1643

src/containers/layout/searchBar/index.js, src/lib/fetchData.js
I don't think there was an open case about it, but this fixes something that always bugged me. Depending on how fast you type into the search box and how fast the backend responds you could get responses back in the wrong order. The result is the autocomplete shows invalid suggestions once you stop typing. 
These changes fix that by aborting the last request if it's still pending before making a new one. Eventually the same concept should probably be applied to all requests we make, but that'll require some more thought and unlike the search box it's hard to trigger page or table requests quickly enough to get into a bad state. These changes also simplify a little of the logic in fetchData.js around timeouts as well.
=> Abort in-flight autocomplete requests before sending new one

src/constants.js, src/containers/wordpress/secondaryNav.js, src/containers/wordpress/style.scss
The actual WordPress page is currently https://alliancegenome.org/working-groups-new this url slug will be changed to working-groups in the WordPress GUI once the code is released.
=> AGR-1707 - condense all Work Products pages into one Working Groups page

src/actions/genes.js, src/components/OrthologPicker.js, src/components/disease/diseaseComparisonRibbon.js, src/components/expression/expressionComparisonRibbon.js, src/lib/createActions.js, src/reducers/geneReducer.js, src/selectors/geneSelectors.js
These changes replace the hardcoded disabled message on species in the ortholog picker with one that takes into account both whether the gene has an ortholog of a given species and optionally whether those orthologs have annotations.
=> Use supplemental data from homologs endpoint

src/components/interaction/genePhysicalInteractionDetailTable.js
Apparently react-bootstrap-table2 swapped the order of the arguments (ie `formatExtraData` and `rowIndex`) passed to the formatter function. If you rely on either argument in react-bootstrap-table1, might want to double check those functionalities.
=> AGR-1717 fix react-bootstrap-table2 breaking interaction tooltip

webpack.config.babel.js
- default `JBROWSE_URL` environment variable to jbrowse-build subdomain
- remove `JBROWSE_PORT` environment variable, as it's no longer being used
=> default to jbrowse-build subdomain

src/components/geneOntologyRibbon/index.js
excludeIBA was a test introduced to see how to remove inferences when showing multiple genes; we now have show experimental annotations only, hence deactivating this
=> excludeIBA removed

package-lock.json, package.json
Buggy, hard-to-reproduce behavior described in AGR-1828 might be caused by a memory leak supposedly fixed in version 8.1.0 (https://github.com/reactstrap/reactstrap/releases/tag/8.1.0). Worth a shot anyway.
=> AGR-1828 Upgrade reactstrap

src/components/dataPage/PageCategoryLabel.js, src/components/dataPage/style.scss, src/containers/allelePage/AllelePage.js, src/containers/diseasePage/index.js, src/containers/genePage/index.js, src/containers/search/categoryLabel.js, src/containers/search/style.scss
Reusing the category label component we already use for search on data pages. @kevinschaper @felixgondwe I reworked the implementation of the category label component but it should still function the same.
=> Add category label to data page headers

src/_theme.scss
Bootstrap automatically sets `box-sizing: border-box` but the ribbon layout assumes otherwise. So manually override the bootstrap setting.
=> AGR-1823 Ribbon requires content-box sizing

src/containers/allelePage/AlleleToVariantTable.js
@sibyl229 I like the default parameter syntax but I guess it only works when the value is `undefined`? So to handle `null` values I guess we just need old fashioned boolean-style checking.
=> AGR-1946 Handle nulls in variant consequence

package-lock.json, package.json, src/containers/genePage/genomeFeatureWrapper.js
https://agr-jira.atlassian.net/browse/AGR-2016
- ~~should have an unknown (black?) and other (?) in the legend~~ (I checked and these were all good as AFAICT)
- ~~make allele of genes unique~~ I think we agreed that this should be done later.
--- 
- ~~pair consequences and impact~~
=> round two of variant fixes

package-lock.json, package.json, src/_theme.scss, src/components/disease/diseaseComparisonRibbon.js, src/components/expression/expressionComparisonRibbon.js, src/index.js
This PR allows the usage of the ribbon web component in both expression and disease ribbons. Aside from ticket 1928, this should take care of : AGR-1565, AGR-1253, AGR-1902. Once the GO ribbon is also integrated (later PR), this will also solve AGR-1471, AGR-1093 and AGR-2000.
**Notes**:
* ~~the “all annotations” selection on startup for disease is not yet working~~
* subjectFocus: the main gene was shown in bold in the previous ribbon, have to reintroduced this capability
* hideFirstSubject: this was used in the old ribbon to show/hide the subject label when only a single gene was shown
* empty cells have a cursor stating not-allowed but under the hood, if one click on that empty cell, an event is still triggered - will correct that at the ribbon level code
=> AGR-1928: integrating the ribbon web component

package-lock.json, package.json, src/components/disease/diseaseComparisonRibbon.js, src/components/expression/expressionComparisonRibbon.js
As requested, this version preventDefault() of the anchor tag and use react router to reroute to the correct alliance page, to avoid page reload.
@paaatrick If you wish, feel free to use other react router functionality.
=> Fix ribbon routing

package-lock.json, package.json, src/components/disease/diseaseComparisonRibbon.js, src/components/expression/expressionComparisonRibbon.js
I added a parameter to prevent an event to be fired on empty cells.
The current behavior differs depending of the selection mode.
If selection mode == cell (go ribbon), no event will be fired on empty cells
If selection mode == column (disease & expression ribbons), an event will be fired if at least one cell of the column has annotations
=> Fix-ribbon-click-on-empty-cells

src/components/dataTable/remoteDataTable.js, src/containers/genePage/alleleTable.js
I also squeezed the alleles table a little so that it doesn't overflow at the maximum viewport width
=> AGR-2204 Prevent scroll indicators from interfering with sort dropdown

package-lock.json, package.json
I noticed that when clicking on "show only experimental annotations", the background color of the cells without annotation were not updated; I fixed it on ribbon code and this is just an update of the package to use.
https://github.com/geneontology/wc-ribbon/commit/35803c1545199f2a0b3b81e5175ff3361730c182
=> Fix ribbon strips update when nb annotations =0

src/components/dataTable/remoteDataTable.js, src/containers/allelePage/AlleleMolecularConsequences.js, src/containers/allelePage/Translation.js, src/containers/allelePage/VariantEffectDetails.js, src/containers/allelePage/VariantToTranscriptTable.js, src/containers/allelePage/style.scss, src/containers/allelePage/translation.scss
- expandable row for molecular consequence details
- wrap at 30 bases instead of 15
- avoid odd wrapping for long sequence
- display end position on the right side of the sequence
=> AGR-2162 vep round 5

package-lock.json, package.json, src/components/geneOntologyRibbon/index.js
This is a major update / fix / clean up of the GO ribbon integration in agr_ui.
The wiring of the GO ribbon was still using old code and old events handling causing various. issues (https://agr-jira.atlassian.net/browse/AGR-2202, https://agr-jira.atlassian.net/browse/AGR-2256).
While fixing https://agr-jira.atlassian.net/browse/AGR-2256, I also added a spinner in the control box (appearing to the right side of the box) whenever the ribbon strips or table is updating. This allows to keep the display on and to update it when the work has finished. Essentially, there are 3 loading parameters: 1 for ribbon strips, 1 for ribbon table and 1 for applying filters (eg orthologs or experimental annotations)
This also solve issue: https://agr-jira.atlassian.net/browse/AGR-1093 on showing GO aspect …
=> Fix AGR-2202, AGR-2256, AGR-1093 and missing functionalities from former PR (MERGE FIRST)

package-lock.json, package.json, src/components/geneOntologyRibbon/index.js
As I thought, I needed a default height for my <li> tags. Long story short, the table directly read the data from the BioLink association model, so the table has some generic grouping/ordering/filtering to achieve the desired results.
When grouping rows based on a column (eg by term), in order to keep the ordering of subcell list (eg 1 cell contains several references), we have to create <li> to keep the table aligned after ordering.
A bit complicated but it does the trick, is generic and can work with any data. Anyhow, it's solved. I also solved an associated issue where we want to display only reference that are PMID/DOI/GO_REF/Reactome.
Off next week
=> AGR-2276 - Fix skewed lines and filter PMID/DOI/GO_REF/Reactome

src/components/disease/diseaseComparisonRibbon.js, src/components/expression/expressionComparisonRibbon.js
Remounting the ribbon component causes its own internal selection state to reset. Even with this fix there is still an issue with getting out of sync as orthologs change which I believe will need to be fixed in the ribbon code. I'll open a separate issue about that.
=> AGR-2202 Do not re-mount ribbon when orthologs change

package-lock.json, package.json, src/components/geneOntologyRibbon/index.js, src/style.scss
This PR fixes AGR-2316 and a few other issues:
* The GO table should not display the "Gene" column as the GO ribbon is designed to handle selection of a single cell and not of a column. This column was simply removed
* I think someone has removed the HOC withRouter of the GO ribbon component as clicking on the gene link to the left of the ribbon strips was now triggering an error (history missing in props) and not rerouting the page to the gene of interest. I don't know what happened, but i re-added the withRouter and this is now working correctly
* updated the NPM package of both the ribbon strips and table and updated the CSS for the GO ribbon table so that the color of the links matches the color of other links on the Alliance pages
=> Fix AGR-2316

src/components/OrthologPicker.js, src/components/dataPage/PageNavEntity.js, src/components/disease/diseaseComparisonRibbon.js, src/components/expression/expressionComparisonRibbon.js, src/components/geneOntologyRibbon/index.js, src/constants.js, src/containers/genePage/index.js, src/lib/utils.js, src/style.scss
Apologies for dumping all these into one branch. When I started I thought there would be fewer changes.
- For AGR-2327 I added a new property to the `SPECIES` objects (`enableSingleCellExpressionAtlasLink`) which controls whether that link is presented on the gene page
- For AGR-2326 I just needed to move a margin CSS class to lower in the tree
- For AGR-2325, the "undefined" string was being produced by the ribbon web component (the species name "SARS-CoV-2" breaks assumptions it has about what species names look like). After talking with Chris Grove, we decided it was best to just do an end run around the immediate problem by 1) ensuring that the gene name label doesn't appear when you're not comparing orthologs (this is good because I believe this was the pre-3.1.0 behavior that may …
=> AGR-2327 AGR-2326 AGR-2325 AGR-2324 SARS-CoV-2 gene page fixes

src/containers/genePage/VariantsSequenceViewer.js, src/containers/genePage/alleleTable.js
In order to support coordination between the variant table and the sequence feature viewer, I'm allowing the Sequence Feature Viewer component some visibility into the table's state. 
I'm spying on the table's representation of filtering, sorting, and pagination, and forward that information on the the Sequence Feature Viewer component. 
Not sure if this is a good idea. Thoughts and suggestions are welcome.
=> AGR-2271 pass table state (filter, sort, and pagination) to sequence feature viewer

package.json, src/containers/genePage/genomeFeatureWrapper.js
Fixes for AGR-2342.  Adding 500bp padding to viewer window and fixed a bug in the viewer for displaying features with no sub-features.
=> Bump Viewer Version and Covid Padding

package.json, src/containers/genePage/genomeFeatureWrapper.js
Reverts alliance-genome/agr_ui#715
=> Revert "Bump Viewer Version and Covid Padding"

src/components/ConstructLink.js, src/components/dataTable/BooleanLinkCell.js, src/components/dataTable/DataTable.js, src/components/dataTable/RotatedHeaderCell.js, src/components/dataTable/RotatedHeaderCell.scss, src/components/dataTable/utils.js, src/containers/allelePage/AlleleTransgenicConstructs.js, src/containers/genePage/TransgenicAlleleTable.js, src/containers/genePage/index.js
@sibyl229 this work contains two components (`RotatedHeaderCell` and `BooleanLinkCell`) that can also be used for the allele and variants table updates. 
The `filterFormatter` bit is something I'm tacking on to the react-bootstrap-table column definition in order to allow for custom formatting of the checkbox filter labels. Here it's being used to translate true/false (which is what the API wants) to Yes/No (which is what the UI needs). The implementation of `filterFormatter` is part of the disease NOT annotation work, but I'm using it here in anticipation that that work will be coming along soon.
=> AGR-2178 Add transgenic alleles table to gene page

package.json, src/containers/genePage/genomeFeatureWrapper.js
Adding in the new version(0.3.9) of the widget and adding a 20% padding for CoV-2 viewer windows.
This update should fix both the axis issue and center the feature.  The layout changes for the widget apply to all isoform viewers (w/o variants) but I can address this in a future update for the other if that would help.
=> GenomeFeatureComponent version bump and padding

src/containers/genePage/genomeFeatureWrapper.js
Decimal values for basepairs in API requests were causing 404's.  Code 
now rounds to whole bp's.
=> AGR-2367 Bugfix

src/components/geneOntologyRibbon/index.js
Essentially, just use catch for fetch functions and add a state "error" to alter the rendering in case of issues.
https://agr-jira.atlassian.net/browse/AGR-2330
Tests:
* HGNC with mapping
/gene/HGNC:11998#function---go-annotations
display correctly
* HGNC without mapping
/gene/HGNC:53833#function---go-annotations
Show "No function available for that gene"
* Regular gene
/gene/ZFIN:ZDB-GENE-990415-270
display correctly
=> AGR-2330 : add error handling when data can not be fetched or ID is missing

src/containers/genePage/genomeFeatureWrapper.js
I don't have a test instance to verify that this change works, but it's pretty simple, so I imagine it will.  It should just add the multiple variant allele track to the "Genome location" jbrowse link.
=> Adding multi-variant track to jbrowse link

src/containers/genePage/VariantsSequenceViewer.js, src/containers/genePage/alleleTable.js, src/containers/genePage/genomeFeatureWrapper.js, src/containers/genePage/index.js
Added in an array prop that holds all of the locations for a specific gene.  This gets propagated down to both genome browser windows.  For examples of this look to HGNC:7082 and HGNC:750.
I'm not sure that I'm using the CommaSeperatedList component exactly correctly.  Things are working but I'm getting a warning about using keys in lists from that specific component.
=> Fixes AGR-2341

src/containers/layout/index.js
I don't know why the timeout was being applied to just the scrolling part and not the element identification part, too. But this should make the anchor link scrolling more reliable.
=> Fix when timeout is applied

src/containers/layout/searchBar/index.js
Hoping to get this into 3.2 as a patch, but leaving this as a draft until we decide to patch or not
=> AGR-2500 Autocomplete falls back to name if name_key isn't available

src/containers/genePage/genomeFeatureWrapper.js
Loading then highlighting was causing the genomeFeatureComponenent to 
not be ready for manipulation... and breaking the highlight.
=> Removed Unnecessary Load

src/containers/GeneAlleleDetailsPage/GeneAlleleDetailsTable.js
**fix missing import of NoData component**
An import statement was missing and somehow the linter didn't catch it.  Without the import statement, the UI would through an error when the API response contains no mapped variant.
**Separate error boundary for viewer and table**
So error in either of the component doesn't break another.
=> error handling for variant details page

src/components/dataTable/DropdownCheckboxFilter.js, src/components/dataTable/utils.js, src/containers/GeneAlleleDetailsPage/GeneAlleleDetailsTable.js
- color code sift and polyphen prediction and score
- add default formatter for column header checkbox
- remove empty value from distinct filter values
@cmpich the empty filter value might concern you, if you intended it to be a feature. But the API doesn't appear to work in that regard. ie. when siftPrediction filter is set to empty value, the response still include those with siftPrediction https://build.alliancegenome.org/api/gene/ZFIN:ZDB-GENE-001212-1/allele-variant-detail?filter.variantSift=&page=1&limit=100&sortBy= . I am omitting the empty values as possible filter values for now. It's likely not very interesting to know what variant has no sift prediction.
=> sift and polyphen display in allele details table

src/containers/GeneAlleleDetailsPage/GeneAlleleDetailsTable.js, src/containers/GeneAlleleDetailsPage/index.js, src/containers/allelePage/VariantSummry.js, src/containers/genePage/alleleTable.js
- Bug in synonym display https://agr-jira.atlassian.net/browse/AGR-2622 
- Title of the details page: "Alleles and Variants details for [gene]"
- Show ‘and’ instead of ‘or’
- Instead of showing the gene in parentheses, show “for”
- The gene could/should link back to the gene page
- Between the sequence viewer and the table, add space or line, currently, it looks like this legend title is the header of the table.
- When there is no data, the details page should be suppressed
- When there is no data, the download on the “genomic variant” section on the Allele page should be suppressed
=> AGR-2535 A series of small fixes for Allele/Variant Details

package-lock.json, package.json, src/components/disease/diseaseComparisonRibbon.js, src/components/expression/expressionComparisonRibbon.js
Yesterday PR on the release branch had two issues:
1. for some reason, the package-lock was using a wrong version of the dbxrefs, which prevented the table to work:
2. end of january, we introduced an auto reload of the ribbon upon subject change (https://github.com/geneontology/wc-ribbon/commit/4e38f384d0be8712c9e633bf2b506acf56fe27e4). So whenever the disease or expression ribbons where updating the list of genes, the ribbon was fetching data from GO, removing the current data. This was fixed by the addition of a new parameter (update-on-subject-change) to prevent those auto reload on subject change: https://github.com/geneontology/wc-ribbon/commit/46bbb2793ecf6d8548c257019940494f3167aa17
Tested locally + run npm tests.
=> Fix AGR-2626 and AGR-2581

src/containers/genePage/alleleTable.js
@cmpich is the alleleCategory filter refer to the non-detailed allele table on gene page? Here is the updated filter name, if I understand it correct.
=> AGR-2637 alleleCategory filter name 

src/containers/genePage/TransgenicAlleleTable.js
Fixing a mistake that changed the same of the cursor when shouldn't. Click on the table shoe does nothing.
=> AGR-2652 turn cursor to normal for a row

package-lock.json, package.json, src/containers/allelePage/AlleleSequenceView.js, src/containers/genePage/genomeFeatureWrapper.js
On allele page filtering transcripts to only include those with 
consequences so that all can be seen.  Also updates widget version to 
0.3.11.
Making a draft until I can do a bit of testing to make sure we haven't introduced bugs.
Fixes bugs discussed in AGR-2483 and AGR-2216
=> Filtering Transcripts

src/containers/GeneAlleleDetailsPage/GeneAlleleDetailsTable.js, src/containers/genePage/VariantsSequenceViewer.js, src/containers/genePage/alleleTable.js, src/hooks/useAllVariants.js, src/lib/utils.js
For gene page and allele-details page for gene.
Forward to viewer via the `allelesVisible` prop up to 1000 alleles based on filtered but not paginated table state.
=> AGR-2676 have viewer share same filter state as table but not pagination state

package-lock.json, package.json, src/containers/allelePage/AlleleSequenceView.js
Fixes 2649.  Needs the latest browser version.  Also fixes an error that we get when an allele has an associated gene but no associated transcripts.
=> AGR-2679 AGR-2538 bugfixes

src/components/dataTable/AlleleCell.js, src/containers/GeneAlleleDetailsPage/GeneAlleleDetailsTable.js, src/containers/allelePage/VariantPage.js, src/containers/allelePage/VariantSequenceView.js, src/containers/allelePage/VariantSummary.js, src/containers/allelePage/VariantToTranscriptTable.js, src/containers/allelePage/getVariantGenomeLocation.js
- fix Gene-Allele details page due to molecularConsequence type change
- variant symbol fallback to displayName and ID
- define variant genome window (for jbrowse and sequence feature viewer) based on gene location, and fallback to +/- 500 bp from the variant.
- increase the column width for feature name (some are really long). (e.g NC_005111.4:g.3276186C>A page)
=> AGR-2864 variant page (round 2)

package-lock.json, package.json, src/containers/allelePage/VariantSequenceView.js, src/containers/genePage/genomeFeatureWrapper.js
Adds browser version 0.3.14 that introduces an optional parameter in 
ISOFORM track views that renders a single SNP onto the viewer.
I've tested this on a few pages but its possible there are fringe cases that I haven't accounted for.  Assuming the variant object has a location parameter it should be passed onto the browser.  This does not make an additional call to apollo since we are currently only rendering the one variant.
=> Adding HTP Variant View

src/public/index.html
Just in case, adding the proper type to the script tag.
Should issues come with that way of loading the reactome widget bundle from a CDN, other possibilites:
* https://www.newline.co/fullstack-react/articles/Declaratively_loading_JS_libraries/
* https://stackoverflow.com/a/60573185
=> AGR-2708 - just adding the type for the script tag

src/containers/GeneAlleleDetailsPage/GeneAlleleDetailsTable.js
Interactive highlight for the details page, such as /gene/ZFIN:ZDB-GENE-070112-172/allele-details
This change enables highlighting in the viewer when rows in the table are clicked on.
`onAllelesSelect` prop is passed to the viewer, which can be called at the time of your choice, to highlight the table rows when variant is selected in the viewer.
=> AGR-2612 details page interactive highlight

src/containers/downloadsPage/index.js, src/containers/layout/ReleaseBanner.js, src/containers/layout/index.js, src/hooks/ReleaseContextProvider.js, src/reactApplication.js, src/tests/application.test.js, webpack.config.babel.js
Use the FMS API to obtain the release version number, which is used to populate both 1) the release number in the website header and 2) the API call for the download page.
ALLIANCE_RELEASE environment variable is no longer in use and is retired.
=> AGR-2667 release version number

src/containers/allelePage/VariantEffectDetails.js, src/containers/genePage/alleleTable.js
Hide allele/variant details link when there are no alleles or variants.
In the code, the alleles is used to refer to both alleles and variants, ie whatever is returned by the /api/gene/ID/alleles endpoint.
=> AGR-2665 hide allele/variant details link when there is no alleles/variants

src/components/dataTable/AnnotatedEntitiesPopup.js
This affects all phenotype and diseases tables that use annotation popups, and makes the experimental condition display available to them, if the data is present in the API response.
=> AGR-2924 experimental condition in annotation popups

src/public/index.html
When JS is disabled in the end-users browser, AllianceGenome.org currently appears as if it's down.  :(
=> add js warning to index.html

package-lock.json, package.json, src/containers/genePage/genomeFeatureWrapper.js
Adding the 0.3.19 browser which adds support for showing multiple rows 
of deletions and setting an initial highlighted state of the browser to keep the view in sync with the table.
Most code changes in the genomeFeatureComponent repo.
=> AGR-2228 AGR-2311 AGR-30587 Adding initialHighlight state and deletion support

package-lock.json, package.json, src/components/pathway/pathwayWidget.js
I was able to introduce a flexible strategy for the GO-CAM viewer. Currently the viewer will take focus:
* after a user stays more than 3s on the component (can be adjusted but 3s sounds a good balance)
* when a user click on the component
I have tried to hijack mouse events for the reactome pathway in different ways, but unfortunately wasn't able to prevent the default behavior. So this will require more discussion with reactome. However, double checking the current behavior, they don't automatically capture the mouse wheel either, they probably even require 3-5s to capture it, so it should not bother the casual scroll of the page.
=> Partial fix for gocam mouse over

src/components/pathway/pathwayWidget.js
On very first load, I find that you might have an issue with the reactome library being loaded from the CDN. So I added an additional check if the Reactome variable is even declared (based on https://stackoverflow.com/a/138883/7608507).
=> AGR-2708: make sure Reactome variable is also declared

package-lock.json, package.json
Added in code for both isoform only and isoform/variant to filter out non-unique transcripts in the widget.  This can be removed once we are sure the GFF and Apollo return is only unique transcripts.  We are filtering on the apollo field ID which in the case of rat is something like rna1234.  If the browser gets to a transcript with an ID that its already seen it will skip it.
No UI codebase changes.
=> AGR-3053 Fixing non-unique transcripts (Rat)

nginx.conf
To hide the Amplify domain name, use a custom domain for the mod-landing-pages.
Update the upstream server for mod-landing-pages (ie. members.alliancegenome.org). So that /members/[something] is proxied to the same path under the subdomain.
=> update reverse proxy for mod-landing-pages 

src/containers/genePage/alleleTable.js
- display allele/variant details link below the summary table (instead of above)
- disable buttons when number of variants is large, and include a note to use the download page instead
=> AGR-3081 allele buttons

apps/main-app/src/containers/modLanding/style.scss
Some changes on banner size, title bar position by increasing `titleBarEmptyRow`. They look quite nice now, with a couple of exceptions but I can modify the original pics to look nicer.
Just a suggestion, you can merge or delete the PR
=> Expanded banner and title invisible bar

apps/main-app/src/containers/genePage/VariantsSequenceViewer.js, package-lock.json, package.json
Fixing link to human jbrowse within browser window and loading error on 
human browser window when variants are requested.
The issue described in KANBAN-33 was due to the "source" for human data being labeled as RGD.  We were building the JBrowse link based on this data.  It now looks at a track level variable to determine which genome to link.  This pull also fixes an issue with the human browser where it was requesting variants from apollo where none exist and failing to load.  Now it does not request these variants and loads fine.  
Also I don't really know who to request reviews for on these sorts of things.... so feel free to redirect this to others.
=> JBrowse Link to Human Fix

apps/main-app/src/containers/genePage/alleleTable.js
Hi @pjhale @oblodgett 
Hope you are well!
Avoiding null/undefined from being passed into the DataTable component appears to fix the issue. 
The error seems to be thrown from BootstrapTable component within DataTable component.
I believe the problem is that while loading data for the table, data=null is passed into the DataTable component, which causes an error to be thrown. This is consistent with the observation that the problem doesn't happen on subsequent loading of the same page, because loading data is nearly instant on subsequent loading due to caching.
That being said, I could no longer access Jira to see the actual bug report. It would be great if one of you could verify if the problem is indeed fixed.
Thanks!
=> fix allele table loading

apps/main-app/src/containers/modLanding/content.js
The wordpress site used as the source for the MOD hex logos has the logos switched for the rodents (i.e., the "mgd.png" is actually the RGD rat, and the "rgd.png" is actually the MGD mouse. If you run this branch locally, and compare it to the current public PROD alliance homepage, you'll see that the logos used in this branch do indeed match what's on the public homepage. I've added a comment in the code to explain the png naming mix up. Ultimately, the wordpress site should be fixed, and/or perhaps we should use assets in this repo for the hex images, rather than external links?
=> fix switched rodent hex logos

apps/main-app/src/components/orthology/constants.js, apps/main-app/src/components/orthology/orthologyUserGuide.js
Reverting the temporary UI changes as we've fixed the spelling of "sonicParanoid" -> "SonicParanoid" in the source data.
=> SCRUM-1219

apps/main-app/src/constants.js
Xenbase added to header and footer via the constants file.
No visible issues with css on both homepage and gene pages.  Both the header and footer are correctly showing the "link out" symbol for the href to xenbase home.  The ticket didn't specify if Xenbase had a longer form label (ex Mouse Genome Database vs MGD) so they are both the same right now.
=> Added Xenbase to header & footer

apps/main-app/src/containers/genePage/genomeFeatureWrapper.js
Added a catch that checks for Laevis taxon and the presence of a chr  prefix.  If this doesn't exit will add.  We can remove this when the  chromosome for laevis matches the JBrowse chromosome.
=> Adding case to add chr prefix to Laevis JBrowse Links

apps/main-app/src/containers/genePage/genomeFeatureWrapper.js
Fixes the JBrowse links for Laevis scaffolds being given the chr prefix. 
Also fixes the display string so these entries don't say 
"ChrScaffold1234".
=> Fix for laevis scaffold issue

apps/main-app/src/components/pathway/pathwayWidget.js, package.json
An updated gocam viz
Only the package version change as it is a component, so no other changes or side effects to agr-ui
As for the GO CAM VIZ changes
- https://github.com/geneontology/wc-gocam-viz/issues/10
- https://github.com/geneontology/wc-gocam-viz/issues/9
- Linear Tree layout
- Gene Panel improvements
- Toggling protein complex view
- small molecules
- other adjustments
- hover over effects (only clicks events)
- the scrolling still lacking, but good enough, but the gene panel will be highlighted
- new decision tree including Constitutively Upstream, remove input for etc
- Group and contributor info
idk who to tag but tagging @kltm @chris-grove @dustine32 @vanaukenk @thomaspd
=> gocam-viz changes: layout, complexes and gene panel

libs/app-shell/src/lib/sitemap.js
Removed #1112 because I was merging into master rather than main. Fixed here. Adds explicit "index.html" to the JBrowse link in the data and tools section
=> addresses https://agr-jira.atlassian.net/browse/KANBAN-318

package.json
[Package Update Commit](https://github.com/geneontology/wc-gocam-viz/commit/629c02a9aaea7fd8c2086172f2695ca18df6a250)
- Fix linkouts to MGI 
- The purple linkouts no more (quick temp solution), to check the GO term linkouts use the inner box
tagging @oblodgett @dustine32 @chris-grove @kltm 
Thanks @chris-grove @dustine32 for feedback and testing it
=> Updated to gocam-viz@0.0.51

apps/main-app/src/components/sequencePanel/sequencePanelSectionHelp.js, apps/main-app/src/containers/genePage/index.js
I’m adding help text for the sequence details section but since I’ve been unable to get the website to run locally I’m committing untested code. I imagine that it is sufficiently simple that I’m likely to get it right, but somebody please really check for real :-)
=> adding help text for seq details.

package.json
For https://github.com/geneontology/wc-gocam-viz/issues/34.
This change should result in the GO-CAM pathway viewer on an Alliance gene page now displaying "Has Input" and "Has Output" relation symbols in the legend.
Thanks @oblodgett!
=> Bump wc-gocam-viz version in package.json

src/components/pathway/pathwayWidget.js, src/style.scss
Additional changes made by @tmushayahama for the setup of the newer `wc-gocam-viz: 1.0.0` package for #1272.
The deleted attributes such as `show-has-input`, `show-activity`, and `repository` are not used.
=> Add more config and styling for pathway widget update

src/components/variant/VariantJBrowseLink.js
Adds some space on the sides when linking to a highlighted variant (this buffering is done with other JBrowse links but wasn't done here, so fixing that),
=> improving the buffer around genes when highlighting a variant

src/components/orthology/orthologyJBrowseLinkPanel.js, src/constants.js
This fixed the pink error box for SARS-CoV-2 and suppresses the jbrowse orthology link panel (the thing that says 'links to jbrowse orthology tracks' at the bottom of the orthology panel) for SARS-CoV-2 since there isn't any tracks like that available.
=> Fix jbrowse covid

package-lock.json
Bumped all versions in the lockfile to include generic-sequence-panel `1.7.0`, which replaced usage of `reactstrap` with `bootstrap-react` to enable react 19 support (once all other dependencies have been updated to versions supporting react 19 as well).
=> generic-sequence-panel upgrade

src/containers/genePage/genomeFeatureWrapper.js
Replaces sequence viewer with under construction message.
I created a flag for clarity, but it is likely something we will never actually toggle, but remove entirely once Apollo is back up and running
=> Kanban 686

package.json, src/style.scss
From this PR https://github.com/alliance-genome/agr_ui/pull/1441
- Updated the wc-gocam-viz component to the latest version (v1.1.2)
- Implemented using the AGR color theme blueish (#2598C5). Check if it matches
- Standardized component's font sizing to 1rem and using rem units throughout for better scaling
The updates include improvements from versions 1.1.1 and 1.1.2:
- [v1.1.1 Release Notes](https://github.com/geneontology/wc-gocam-viz/releases/tag/v1.1.1)
- [v1.1.2 Release Notes](https://github.com/geneontology/wc-gocam-viz/releases/tag/v1.1.2)
For more detailed information about the issues resolved in these updates, please see the [technical announcement](https://github.com/geneontology/go-technical-announcements/issues/2).
cc @vanaukenk  @kltm @dustine32
=> Update wc-gocam-viz component to v1.1.2 with AGR color theme to test

src/components/pathway/pathwayWidget.js
This is for geneontology/go-fastapi#114. See also https://github.com/geneontology/api-gorest-2023/issues/3#issuecomment-2777095671.
This change should result in same behavior/results that `.xyz` is delivering but, in the future, we plan on maintaining only the GO API and deprecating the `api.geneontology.xyz` endpoint. @vanaukenk and @kltm can fill in more details if needed.
I tested this change by running a local server instance and confirming models are returned on gene page pathway widget GO-CAM tab for genes [Ern1 Mmu](https://www.alliancegenome.org/gene/MGI:1930134) and [dkf-2 Cel](https://www.alliancegenome.org/gene/WB:WBGene00012019).
=> Switch xyz to GO API for geneontology/go-fastapi#114

.github/workflows/claude-review.yml
- Remove hardcoded pr_size_threshold and skip_threshold
- Let workflow inherit defaults from alliance-genome/.github
- Centralized thresholds: skip ≤3 lines, zen >40 lines
- Supports Skip 10%, Zen 50% strategy across all repos
=> Use centralized Claude review thresholds from .github repo

src/containers/alzheimersPage/DiseasePortalSection.jsx, src/containers/alzheimersPage/ResourcesSection.jsx, src/containers/alzheimersPage/useEntityButtonCounts.jsx
This PR ports user-facing features that were completed in the test branch (June 2025) but never made it to stage due to branch divergence after the major refactoring.
- **KANBAN-428**: Display model counts
- **KANBAN-429**: Display gene counts  
- **KANBAN-430**: Display allele counts
- **KANBAN-655**: Add NIAGADS URL to Alzheimer's Disease landing page
✅ Created `useEntityButtonCounts.jsx` hook for fetching entity counts dynamically
✅ Updated `DiseasePortalSection.jsx` to display live counts instead of hardcoded values
✅ Added NIAGADS resource URL to `ResourcesSection.jsx`
✅ Fixed typo: "Community Resoures" → "Community Resources"
These features were stuck in the test branch after Seth's major refactoring that renamed all `.js` files to `.jsx`. Due to the extensive file changes (553 …
=> Port missing features from test branch to stage

amplify.yml
When NODE_ENV=production, npm skips devDependencies which includes TypeScript, Vite, and other build tools. This causes the build to fail.
This fix uses 'npm install --no-save' to install the minimal required build dependencies locally without modifying package.json, allowing the build to complete while maintaining NODE_ENV=production for runtime.
Required packages:
- typescript (for tsc compilation)
- vite (build tool)
- @vitejs/plugin-react (vite plugin for React)
These are installed after the main npm install to ensure they're available for the build phase.
=> Fix Amplify production build with NODE_ENV=production

amplify.yml
The production Amplify build was failing with "tsc: command not found" because when NODE_ENV=production is set, npm v10 skips installing devDependencies where TypeScript, Vite, and other build tools are defined.
Temporarily unset NODE_ENV only during npm install commands by using `unset NODE_ENV && npm install`. This allows npm to install all dependencies including devDependencies, while preserving NODE_ENV=production for the build and runtime phases.
- The `unset NODE_ENV` only affects the single chained command, not the entire environment
- NODE_ENV=production remains set for all subsequent commands (build, deploy, runtime)
- This ensures we get build tools during install but maintain production optimizations
While Vite handles build optimizations automatically (vite build always …
=>  Fix Amplify production build failure caused by missing TypeScript
