src/constants.js
src/containers/search/multiTable.js

Enough to get the disease category label decorated nicely, and the disease table to show up

AGR-519   Re-added basic disease support to search

---

src/containers/layout/menu.js
src/containers/layout/navLink.js
src/containers/layout/navLinksContainer.js
src/containers/layout/siteMap.js

Refactored : 
1.  layout/menu.js and 
2. layout/siteMap.js 
Created two new react components : 
1.  layout/navLink.js
2. layout/navLinksContainer.js

Fixed broken links for News and Events - Agr 531

---

src/actions/disease.js
src/components/collapsibleList.js
src/components/primaryAttributesList.js
src/components/style.css
src/containers/diseasePage/basicDiseaseInfo.js
src/containers/diseasePage/index.js
src/containers/genePage/basicGeneInfo.js
src/containers/genePage/dataSourceCard.js
src/reducers/diseaseReducer.js
src/reducers/index.js
src/selectors/disease.js

This adds a new component for displaying primary attributes tables. Gene page has been updated to use it and it is also used on the disease page.

AGR-542 Add basic disease info section to disease page

---

src/containers/search/filterSelector/filterSelector.js
src/containers/search/filterSelector/singleFilterSelector.js

Just shows more facet values for species facets

AGR-493  Show more values for any species facet

---

src/containers/genePage/genomeFeatureViewer.js
src/containers/genePage/style.css

fixed links for rat and human, used bootstrap error, and removed json link

fixed links for rat and human links, used bootstrap error, and removed json link

---

src/components/orthology/orthologyUserGuide.js

https://agr-jira.atlassian.net/browse/AGR-590
AGR-590

update orthology user guide for new set of algorithms

---

src/containers/search/resultsList.js
src/containers/search/resultsTable.js

Get synonyms to show up as a highlight in list view
Remove synonyms from disease table
Change OMIM ID to ID

AGR-605  disease related highlighting fixes

---

src/containers/diseasePage/basicDiseaseInfo.js

"lenth"... i am not a smart man 😢

Fix red error flash when disease page loads

---

package.json

At least this gets the site up... will need to address this in the next couple of days.

Revert pull request

---

src/components/style.css
src/containers/genePage/genomeFeatureViewer.js

Fixes AGR-648 and AGR-656
Replaces #93.

Fix genome features - Fixes AGR-648 and AGR-656

---

src/containers/layout/searchBar/index.js

It's pretty complicated, if you have any questions, I can point you to the Knuth books that I got the algorithm from.

AGR 680  update placeholder to include disease

---

src/components/genomeFeature/GenomeFeature.js
src/containers/layout/navLinksContainer.js

fixes AGR-702 and cleans up  lifting error

properly handling introns and other non-rendered types

---

src/components/genomeFeature/GenomeFeature.js

Fixes scale shown for small and large ranges of genome features.

fixed some scaling and clumping issues

---

src/containers/genePage/genomeFeatureViewer.js
src/containers/genePage/index.js

Fix AGR-709 , highlighting for C. elegans  
FYI @scottcain

fixed C. elegans

---

package.json

* to include Suzi's fix on "coloring for the GO results for human query"

update go-ribbon version

---

src/components/genomeFeature/GenomeFeature.js

I feel there is probably a better way to do this, but there it is.  
pinging @pjhale

added fix for AGR-725

---

src/components/style.css
src/containers/layout/style.css
src/containers/wordpress/style.css
src/containers/wordpress/wordpressPage.js

@paaatrick  made the requested changes. But the sub-nav links still seem to have more padding than
their parents - 
Removed the nav background on mouse hover --

Agr 672 - Fix the Main menu style

---

src/containers/genePage/genomeFeatureViewer.js
src/containers/genePage/index.js

Fixes last remaining bug with AGR-674

fixes trying to provide an overview for non-coding types

---

src/components/genomeFeature/GenomeFeature.js
src/containers/genePage/genomeFeatureViewer.js
src/containers/genePage/index.js

fixes:
https://agr-jira.atlassian.net/browse/AGR-711
https://agr-jira.atlassian.net/browse/AGR-709
https://agr-jira.atlassian.net/browse/AGR-748
@pjhale   Note the sorting I do for selected vs non-selected widgets.   Other than that there should be no changes to the widget.

Fix highlighting

---

bin/build_sitemap.js
src/components/externalLink.js
src/constants.js
src/containers/layout/navLinksContainer.js
src/containers/layout/subMenu.js
src/containers/wordpress/index.js
src/containers/wordpress/secondaryNav.js
src/routes.js
webpack.config.babel.js

All the routes to Wordpress pages are now using the page slug - 
Also as per last meeting - November 1st - I worked on the menu items to make it look less
crowded :)

Agr 743 -Use Wordpress page slug in all react routes mapping to Wordpress pages

---

src/containers/wordpress/index.js
src/routes.js

The root of the site should be set back to /

Restored indexRoute mapping to the root of the site

---

src/components/orthology/orthologyUserGuide.js

fix typo in Ensembl

---

src/components/orthology/orthologyBasicInfo.js
src/components/orthology/orthologyFilteredTable.js
src/containers/genePage/index.js

AGR-759 orthology table control re-organized

---

src/components/orthology/constants.js
src/components/orthology/orthologyFilteredTable.js
src/components/orthology/orthologyTable.js
src/components/orthology/orthologyUserGuide.js

Update filter for orthology table: https://agr-jira.atlassian.net/browse/AGR-820
Update algorithm for diopt: https://agr-jira.atlassian.net/browse/AGR-845
Fix diopt link: https://agr-jira.atlassian.net/browse/AGR-728

Orthology table changes

---

src/components/orthology/orthologyFilteredTable.js

Default view:
After user clicks on "Show additional filters":

AGR-820 orthology table fixes and UI improvements

---

src/components/dataTable/downloadButton.js
src/components/dataTable/localDataTable.js
src/components/dataTable/remoteDataTable.js
src/components/disease/genePageDiseaseTable.js

This fixes downloading the gene page disease table (and reuses the component that the disease page table uses).

AGR-861 Fix gene page disease download

---

src/components/crossReferenceList.js
src/components/dataSourceLink.js
src/components/orthology/pantherCrossRef.js
src/components/subsection.js
src/containers/diseasePage/basicDiseaseInfo.js
src/containers/diseasePage/index.js
src/containers/genePage/basicGeneInfo.js
src/containers/genePage/expressionLinks.js
src/containers/genePage/index.js

This has a known issue that the SPELL and GEO links in the Other Sources section aren't showing with the desired link text. I'm working with the other technical groups to get that worked out, but I'd like to get this initial version in for now so folks can start checking it out.

AGR-777 Initial version of expression section on gene page

---

src/lib/searchHelpers.js
src/reducers/searchParsers.js

also added pretty field renaming for localId cross reference matches

AGR-934  Fixed cross reference parsing

---

src/containers/search/resultsList.js
src/containers/search/searchControls.js
src/containers/search/style.css

-css changes to fix category icon bug

AGR-869 fix

---

src/containers/genePage/expressionLinks.js

Small change requested from the Expression WG based on testing

Hide GEO links when more than one exists

---

src/lib/searchHelpers.js
src/reducers/searchParsers.js

(aka hide duplicates from multi-fields)

AGR-956 Only show one highlight for each 'super' field 

---

package.json

address a few problems identified here:
https://agr-jira.atlassian.net/browse/AGR-973
and it makes testing easier.  
fixes from here: 
https://github.com/geneontology/ribbon/issues/41
and 
here:
https://github.com/geneontology/ribbon/issues/40
and ribbon changes here:
https://github.com/geneontology/ribbon/commit/8228b3ced7231860a9f9627ab791fc3480828b1f
https://github.com/geneontology/ribbon/commit/17779e02ce46f71e1e278e42cc002ee3e5e95ed0

Agr 973 v1

---

src/containers/genePage/genomeFeatureViewer.js
webpack.config.babel.js

Not that I do much with this repo.

Added apollo integration

---

webpack.config.babel.js

Fixes error introduced here:
https://github.com/alliance-genome/agr_ui/pull/243
Should have tested it.   I have tested this fix and seems to work.

fixed missing apollo-env-url

---

package.json
src/components/geneOntologyRibbon/index.js
src/index.js

integrates with version 1.4.4 of the Ribbon.  Had to make a few other changes.  
https://www.npmjs.com/package/@geneontology/ribbon
https://github.com/geneontology/ribbon

adding ribbon updates

---

package.json
src/containers/genePage/index.js

Couple of small fixes for AGR-1038

AGR-1038 Pheno table fixes

---

src/lib/searchHelpers.js

Ideally this should get pulled alongside AGR-940 in agr_java_software, but it'll only be mildly broken if they're out of sync

AGR-940  Updated pretty field names for GO facets on genes

---

package.json

fixes for  AGR-1056, AGR-1057, AGR-1058, AGR-1059

fixes for  AGR-1056, AGR-1057, AGR-1058, AGR-1059

---

src/containers/search/resultsList.js
src/lib/searchHelpers.js

(and a small fix for dumb missing text output)

AGR-1048  automatic pretty-field string conversion for camelCase

---

package.json

fix for AGR-1098 and AGR-1099 in

added bounced version

---

src/components/dataPage/dataPage.js
src/components/headMetaTags.js
src/containers/genePage/index.js

just a reference for this proposal:
https://agr-jira.atlassian.net/browse/AGR-1160
will close for now, but I find its easier to look at code.
Would need to replicate for the disease page if we go forward.

initial implementation of  AGR-1160 - google structured data

---

src/components/headMetaTags.js

release to push to production sooner than later:
https://agr-jira.atlassian.net/browse/AGR-1160

Patch release 1.8.0 v1

---

package.json
src/components/geneOntologyRibbon/index.js
src/containers/genePage/index.js

Upgrading to the latest version of the ribbon. There's an issue with the evidence code filter box getting clipped by the horizontal scroll container, but we can work that out separately.

Upgrade ribbon 1.5.2

---

src/components/orthology/constants.js
src/components/orthology/methodCell.js
src/components/orthology/methodLogo.js

(for 1.8) fix issues caused by method name changes (AGR-1177)

---

src/lib/searchHelpers.js

@paaatrick Critique my loop please.

AGR-1196  Simplified field name prettification for GO & UBERON facets

---

.gitignore
package.json
src/actions/expression.js
src/components/controlsContainer.js
src/components/dataTable/remoteDataTable.js
src/components/expression/annotationTable.js
src/components/expression/expressionComparisonRibbon.js
src/components/expression/index.js
src/components/expression/summaryRibbon.js
src/components/geneOntologyRibbon/index.js
src/components/loadingSpinner.js
src/components/orthology/constants.js
src/components/orthology/index.js
src/components/orthology/orthologyFilteredTable.js
src/components/orthology/orthologyTable.js
src/components/orthology/stringencySelector.js
src/constants.js
src/containers/genePage/genomeFeatureViewer.js
src/containers/genePage/index.js
src/containers/search/filterSelector/singleFilterSelector.js
src/index.js
src/lib/fetchData.js
src/lib/tests/store.test.js
src/lib/tests/utils.test.js
src/lib/utils.js
src/reducers/expressionReducer.js
src/reducers/index.js
src/selectors/expressionSelectors.js
src/selectors/geneSelectors.js

Mostly this is new code. It did touch some existing code to facilitate sharing code between this and the orthology section.
Also takes care of some issue that came in from early testing: AGR-1207, AGR-1206, AGR-1205, AGR-1204, AGR-1212.

AGR-1138 Add comparison ribbon interface to expression section

---

src/components/dataPage/dataPage.js
src/components/errorBoundary.js
src/components/subsection.js

Note you won't be able to test with the webpack-dev-server running:
To test:
- Introduce some error in a page subsection
- `npm run build`
- Install and run a HTTP server
```
npm install http-server -g
http-server dist/ -p 2991 -P http://www.alliancegenome.org
```
An example screenshot:

Agr 1235 error boundary

---

src/components/expression/annotationTable.js
src/components/style.scss
src/components/subsection.js
src/containers/genePage/index.js

I also snuck in a fix to get rid of a proptypes error about missing children.

AGR-1236 Use comma-separated list for expression cross refs

---

src/components/expression/expressionComparisonRibbon.js
src/components/expression/summaryRibbon.js
src/lib/utils.js

* leave human genes out of the ortholog gene picker
* show a warning message about not having expression data on human gene pages when orthologs have not been selected
* show grey blocks in ribbon on human gene pages when ortholog have been selected

AGR-1252 Special casing for human genes

---

src/components/genomeFeature/GenomeFeature.js

fixes https://agr-jira.atlassian.net/browse/AGR-1247

properly displays genes without sub-feature exons

---

src/components/dataLoader.js

show "no data available" when data from DataProvider is empty array 

---

src/components/interaction/genePhysicalInteractionDetailTable.js

reorder columns for physical interactions detail table

---

src/lib/genomeFeatureTypes.js

fixes it:
https://agr-jira.atlassian.net/browse/AGR-1293

added fix for AGR-1293

---

src/components/scrollToTop/index.js
src/containers/layout/searchBar/index.js
src/containers/search/categoryLabel.js
src/containers/search/resultsList.js
src/containers/search/style.scss
src/reducers/searchParsers.js

With a real => function and a change so that ScrollToTop cares about search as well as pathname

AGR-947 Support for related data links between search results

---

src/components/dataTable/CellTooltip.js

https://agr-jira.atlassian.net/browse/AGR-1312?focusedCommentId=20103&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-20103

prevent tooltop flashing due to tooltip interfering with mouse event

---

src/components/headMetaTags.js

Jsonld agr 1318 agr 1319 agr 1345

---

.gitignore
package-lock.json

check in package-lock.json, which is the single source of truth of the package version to install

Fix dependency change causing broken build

---

changes.md
package.json

Last piece to fix this: 
https://agr-jira.atlassian.net/browse/AGR-1146
ATTN @sibyl229

uses component which automatically fixes the height - AGR-1146

---

src/components/interaction/genePhysicalInteractionDetailTable.js

Agr 793 interactions fewer columns

---

package-lock.json
src/components/expression/expressionComparisonRibbon.js

Fix error when clicking "Add all" button with no orthologs (AGR-1302)

---

src/components/interaction/genePhysicalInteractionDetailTable.js

Agr 793 change interaction table source column display

---

src/containers/homepage/index.js
src/containers/homepage/style.scss

Reduce the size of the slide logos so it doesnt take up all the things

---

src/components/interaction/genePhysicalInteractionDetailTable.js

AGR-793 fix interaction ui for API change

---

src/lib/utils.js

AGR-1132  use stringency level returned by the API

---

package.json

Actually, this has an impact on your git process. You probably want to try it before merging this in.

fix package-lock.json keeps changing between http and https based URL

---

package-lock.json
src/components/interaction/geneInteractionCrossReference.js
src/components/interaction/index.js
src/containers/genePage/index.js

- can only be tested once data is coming through from alliance-genome/agr_loader#372
- this PR is ready for the code freeze

AGR-1135 interaction link out to MODs

---

package-lock.json
package.json
src/components/expression/expressionComparisonRibbon.js
src/components/expression/summaryRibbon.js
src/components/geneOntologyRibbon/index.js
src/style.scss

… summaryRibbon
@paaatrick and/or @oblodgett could you check this PR please ? 
I had to adjust the summaryRibbon component to use the new data model (entities that each contain blocks, rather than blocks directly, therefore allowing for multiple entities).
I have added one parameter in the expression ribbon `onClick` method for your lazy loading, since the method now return both the selected entity and the block (before only block)
There are various ways to tweak the appearance (see style.css where I import the main sass file), but we can always adjust during this test phase or for the 2.2 release .

Using the new Ribbon (1.9.2): appearances, multi entities, correcting…  (AGR-1055, AGR-958, AGR-1203, AGR-1325)

---

package-lock.json
package.json

also check hat Other category is working and showing only unmapped terms
Fix on the ribbon master: https://github.com/geneontology/ribbon/pull/92

Correct the redundancy in "All" section slim box (MERGE SECOND)

---

src/components/expression/summaryRibbon.js

+ following new conventions for "All" section slim box

Improving the SummaryRibbon intermediary object (MERGE THIRD)

---

package-lock.json
package.json

Simple fix to fetch data from api.geneontology.org rather than the old default monarch
Should improve availability

Ribbon go api

---

.babelrc
package-lock.json
package.json
src/components/dataPage/style.scss
src/index.js

@sibyl229 apologies for undoing some of your recent work with this PR! I couldn't seem to get ES6 builtin functions (like `Object.assign`) working with the `babel-preset-react-app` preset. I kept getting errors about duplicate babel polyfill libraries being loaded. If you have other suggestions, please let me know or add commits to this branch.

AGR-1522 IE11 fixes

---

webpack.config.babel.js

when clicking on the JBrowse link it goes to the wrong place . . this makes it go to the right place

fix jbrowse location

---

package-lock.json
package.json
src/components/geneOntologyRibbon/index.js

For daily build, do you want us to do PR over master or another branch ?
Thanks

Reusing hasBlockData and updating Ribbon version (AGR-1531 - MERGE FIRST)

---

package-lock.json
package.json

https://github.com/geneontology/ribbon/pull/95/files

Fix "other" as part of "all" (AGR-1539 - MERGE SECOND)

---

package-lock.json
package.json

https://github.com/geneontology/ribbon/pull/97/files

Correct the links to qualifiers (AGR-1536 - MERGE THIRD)

---

package-lock.json
package.json

https://github.com/geneontology/ribbon/pull/98

Filter dropdown hidden on background click (AGR-1277 - MERGE FOURTH)

---

package-lock.json
src/containers/diseasePage/index.js

fixes https://agr-jira.atlassian.net/browse/AGR-1585?atlOrigin=eyJpIjoiZTc2OTIzMzg1YWQ0NDk4MzkzZmI4NzM0MjQwMzQ4OGQiLCJwIjoiaiJ9

fixes case where synonyms do not exist  AGR-1585

---

src/components/orthology/booleanCell.js
src/components/orthology/orthologyTable.js

AGR-518 display and help text for yes_adjusted

---

src/components/dataTable/index.js
src/components/dataTable/remoteDataTable.js
src/components/dataTable/tableSummary.js
src/components/disease/genePageDiseaseViaExperimentTable.js
src/components/disease/genePageDiseaseViaOrthologyTable.js
src/components/interaction/genePhysicalInteractionDetailTable.js
src/containers/genePage/phenotypeTable.js
src/lib/handleActions.js

AGR-1383
- interactions
- phenotype
- diseases (UI implemented, but API not sending back data yet)

AGR-1383 add "X number of annotations for Y number of [entityType]"

---

src/components/dataTable/columnHeader.js
src/components/dataTable/dropdownCheckboxFilter.js
src/components/dataTable/filterSets.js
src/lib/utils.js

This also keeps the use of the Immutable List internal to the checkbox filter state

AGR-1605 Use display names in filter

---

src/components/disease/diseaseAnnotationTable.js
src/containers/diseasePage/diseasePageAssociationsTable.js

AGR-1604  AGR-1619  Use checkbox filters on disease table columns

---

package-lock.json
package.json

https://agr-jira.atlassian.net/browse/AGR-1618

Fixed version of the ribbon (ALL box previously not selected on click)

---

src/components/disease/diseaseComparisonRibbon.js

https://agr-jira.atlassian.net/projects/AGR/issues/AGR-1631?filter=allopenissues&orderby=priority%20DESC

Fix AGR-1631

---

src/components/disease/diseaseAnnotationTable.js
src/components/disease/diseaseComparisonRibbon.js

Harmonize expression & disease ribbons when no data available upon table filtering

Fix AGR-1632

---

package-lock.json
package.json
src/components/disease/diseaseAnnotationTable.js
src/components/disease/diseaseComparisonRibbon.js

Open disease ribbon link in current tab rather than new tab
Ribbon commit to add the functionality: https://github.com/geneontology/ribbon/commit/f2cbea11afcfc9008f391f5b19be1c3057775cfc

Fix AGR-1628

---

README.md
src/actions/disease.js
src/components/disease/diseaseAnnotationTable.js
src/components/disease/genePageDiseaseViaExperimentTable.js
src/components/expression/annotationTable.js
src/components/orthology/booleanCell.js
src/containers/layout/twitterWidget.js

- Add missing columns, remove console log
- No known side effects

Fix AGR-1616, AGR-1608

---

src/components/disease/diseaseComparisonRibbon.js

The ribbon css will be revisited for the next release as this 'intermediary' ribbon is a bit clanky in its way to use the old ribbon css in order to keep a same overall design.

Fix AGR-1647

---

src/components/dataTable/basedOnGeneCell.js
src/components/dataTable/index.js
src/components/disease/diseaseAnnotationTable.js

AGR-1611, AGR-1659 Fix BasedOn Column & GeneEntityType filter

---

src/containers/wordpress/style.scss

Updated banner images for News, Help and Contact Us pages.

AGR-1706 - update banner images

---

package-lock.json
package.json
src/components/OrthologPicker.js
src/components/dataTable/filterSets.js
src/components/disease/diseaseAnnotationTable.js
src/components/disease/diseaseComparisonRibbon.js
src/components/expression/expressionComparisonRibbon.js
src/constants.js
src/lib/utils.js
src/style.scss

These changes:
* make the stringent ortholog set added for comparison by default
* display the table of all disease annotations by default
* update the ortholog picker for both expression and disease to be more oriented toward adding/removing sets of genes

AGR-1696 AGR-1697 Update default state of disease comparison ribbon

---

src/components/alleleTable/index.js
src/components/dataTable/columnHeader.js
src/components/dataTable/remoteDataTable.js
src/components/dataTable/style.scss
src/containers/genePage/index.js

Adding variants display to alleles table on gene page

AGR-1574 variants

---

src/components/crossReferenceList.js
src/containers/genePage/expressionLinks.js
src/containers/genePage/index.js

Also adds Single Cell Atlas links

AGR-1015 AGR-1406 Add link back to expression images at MODs

---

package-lock.json
src/components/alleleTable/index.js
src/components/dataSourceLink.js
src/containers/genePage/genomeFeatureWrapper.js
src/containers/genePage/index.js
src/containers/genePage/phenotypeTable.js

The build site is kinda broken right now. The root cause is probably on the API side, where things that should be arrays or objects are null or undefined. They cause the UI code to break.
I'm just putting in some defensive mechanism to handle the nulls and undefined, so UI development can happen, while things are being fixed on the API side.

Handle nulls and undefined

---

src/containers/layout/searchBar/index.js

rather than a mix of primaryKey and primaryId

Updated autocomplete code to match search backend always using primaryKey 

---

package-lock.json
package.json
src/components/disease/diseaseComparisonRibbon.js
src/components/expression/expressionComparisonRibbon.js
src/components/geneOntologyRibbon/goControlsHelp.js
src/components/geneOntologyRibbon/goUserGuide.js
src/components/geneOntologyRibbon/index.js
src/lib/fetchData.js

New ribbon version
* GO & orthology picker
* ability to select cell or column in the ribbon
* some GO documentation / user guide
DONE:
* changing axios to fetchData

go ribbon + selection (cell/column)

---

src/components/geneOntologyRibbon/index.js

fetchData for association table was still using data.data

fetchData -> data.data to data

---

src/components/geneOntologyRibbon/index.js

Fix two issues:
* click "All" annotations wasn't working anymore due to a new filter and missing test case
* not all annotations were retrieved (only from the first aspect)

AGR-1771 : fix "All" annotations 

---

src/components/alleleTable/index.js

PR created to fix AGR-1768

---

src/components/geneOntologyRibbon/index.js

I will have to fix the API summary query as the number displayed doesn't match. It will be fixed on the API side and not agr_ui

Fixing the "other" category association tabler

---

package-lock.json
package.json

Fix by:
* https://github.com/geneontology/ribbon/commit/c680d52041d863865ae5ec2d52f6f5350122fc1c
* API update for the ribbon summary route

AGR-1774 fix - updated ribbon

---

src/components/OrthologPicker.js

This year's Nobel Prize in Computer Science

AGR-1805 Any -> No filter

---

src/components/alleleTable/index.js

fix for https://agr-jira.atlassian.net/browse/AGR-1768  second one.
Still an error in calculating an insertion.

fixes AGR-1768 a second time

---

package-lock.json
package.json
src/components/expression/expressionComparisonRibbon.js

**Warning!!!** Merging this without the GO fix would break the UI
I un-commented the changes @paaatrick made on the default expression slim for yeast.

AGR-1827 (Warning: GO ribbon fix needed before this should be merged) expression categories

---

src/containers/genePage/genomeFeatureWrapper.js

patches: https://agr-jira.atlassian.net/browse/AGR-1910

fixes AGR-1910

---

src/actions/alleleActions.js
src/containers/allelePage/AllelePage.js
src/containers/allelePage/AlleleToDiseaseTable.js
src/reducers/alleleReducer.js
src/selectors/alleleSelectors.js

The download endpoint isn't implemented yet, but I'm putting the button there with the good faith assumption that it will be there soon (AGR-1912)

AGR-1922 Add table of disease associations to allele page

---

package-lock.json
package.json
src/containers/genePage/genomeFeatureWrapper.js
webpack.config.babel.js

https://agr-jira.atlassian.net/browse/AGR-1851
https://agr-jira.atlassian.net/browse/AGR-1917

Agr 1917 v1

---

src/containers/genePage/genomeFeatureWrapper.js

fixes https://agr-jira.atlassian.net/browse/AGR-1937

URI encodes names so we do not have bad names

---

webpack.config.babel.js

Fixes:
https://agr-jira.atlassian.net/browse/AGR-560

added apollo to docker now   AGR-560

---

src/components/RibbonGeneSubjectLabel.js
src/components/disease/diseaseComparisonRibbon.js
src/components/expression/expressionComparisonRibbon.js
src/components/geneOntologyRibbon/index.js
src/components/style.scss

Also highlights the focus gene as suggested in the case

AGR-1856 Enable ortholog compare by default for expression

---

src/containers/allelePage/AlleleSequenceView.js
src/containers/genePage/genomeFeatureWrapper.js
src/containers/genePage/index.js

fixes:
https://agr-jira.atlassian.net/browse/AGR-1953
https://agr-jira.atlassian.net/browse/AGR-1952
https://agr-jira.atlassian.net/browse/AGR-1948

Fix AGR-1948 AGR-1952 AGR-1953

---

package-lock.json
package.json

bumped gcf to 0.2.11

---

src/containers/genePage/genomeFeatureWrapper.js

fixes AGR-1968
https://agr-jira.atlassian.net/browse/AGR-1968

fixes AGR-1968

---

package.json

fixes https://agr-jira.atlassian.net/browse/AGR-1967

Fix agr 1967

---

package.json

fixes https://agr-jira.atlassian.net/browse/AGR-1957

Fix AGR-1957

---

package-lock.json
package.json
src/containers/genePage/genomeFeatureWrapper.js

https://agr-jira.atlassian.net/browse/AGR-1983

fixes AGR-1983

---

package-lock.json
package.json
src/containers/genePage/genomeFeatureWrapper.js

fixes https://agr-jira.atlassian.net/browse/AGR-1992

Fix AGR-1992

---

src/containers/genePage/VariantsSequenceViewer.js
src/containers/genePage/index.js

fixes https://agr-jira.atlassian.net/browse/AGR-1998

Fix AGR-1998

---

package-lock.json
package.json

fixes https://agr-jira.atlassian.net/browse/AGR-2002

Fix agr 2002

---

package-lock.json
src/constants.js
src/containers/search/detailList.js
src/containers/search/resultsList.js
src/reducers/searchParsers.js

AGR-2031 Fixed GO Branch display / re-allowed duplicate highlighting for synonyms field

---

package-lock.json
package.json

Fixes: 
https://agr-jira.atlassian.net/browse/AGR-2091

Fix AGR-2091

---

src/constants.js
src/containers/search/detailList.js
src/lib/searchHelpers.js
src/reducers/searchParsers.js

AGR-2111 simplification of cross reference handling in search

---

src/containers/genePage/genomeFeatureWrapper.js
src/lib/genomeFeatureTypes.js

Fixes:
https://agr-jira.atlassian.net/browse/AGR-2032

adds more transcript types to view to fix AGR-2032

---

package-lock.json
package.json

bump in version for GenomeFeatureComponent fixes https://agr-jira.atlassian.net/browse/AGR-1989

bumped version to make it work properly

---

package-lock.json
package.json
src/containers/genePage/VariantsSequenceViewer.js
src/containers/genePage/alleleTable.js
src/containers/genePage/genomeFeatureWrapper.js

this provides a hook into the GFC component as part of:
https://agr-jira.atlassian.net/browse/AGR-2038

Send props to gfc

---

package-lock.json
package.json
src/containers/allelePage/AlleleSequenceView.js
src/containers/genePage/VariantsSequenceViewer.js
src/containers/genePage/genomeFeatureWrapper.js

fixes: https://agr-jira.atlassian.net/browse/AGR-1947

added set visible alleles initial fix

---

src/components/collapsibleList/collapsibleList.js
src/components/dataTable/referenceCell.js

This changes reference lists from comma-separated to a collapsible list. 
It also converts the collapsible list to a functional component using hooks for state.

AGR-1353 Use collapsed list for references

---

src/containers/homepage/ActionButton.js
src/containers/homepage/SearchSection.js
src/containers/homepage/index.js
src/containers/homepage/style.scss
src/containers/layout/style.scss

This includes:
- partial list of searchable data types as search placeholder
- link to search help
- additional text on View Publications and Learn More icon buttons
- un-lightened main call-to-action text
- lightened icon buttons
- COVID-19 landing page link

AGR-2160 AGR-2161 Home page updates

---

package-lock.json
package.json

In the initial fix, I forgot to publish the new NPM package of the ribbon, hence not working.

Fix - AGR 2201 with right NPM package

---

package-lock.json
package.json

fix for https://agr-jira.atlassian.net/browse/AGR-2212

fix for AGR-2212

---

package-lock.json
package.json

brought in GFC change

---

src/containers/genePage/genomeFeatureWrapper.js

fixes https://agr-jira.atlassian.net/browse/AGR-2222

fixed ui bug

---

src/containers/allelePage/AlleleMolecularConsequences.js
src/containers/allelePage/AllelePage.js
src/containers/allelePage/AlleleToVariantTable.js
src/containers/allelePage/Position.js
src/containers/allelePage/VariantEffectDetails.js
src/containers/allelePage/VariantToTranscriptTable.js
src/containers/allelePage/useAlleleVariants.js
src/containers/allelePage/useFetchData.js
src/containers/allelePage/useVariantTranscripts.js

basically moving things around and re-phrasing things as requested

AGR-2162 VEP round 2

---

src/containers/allelePage/VariantEffectDetails.js

- collapsible hgvs names
- reorder some of the attributes

AGR-2162 round 4 

---

src/containers/allelePage/Translation.js

- allow on/off for start and end position in TranslationRow
- display start position only for first row of sequence and end position for last row of sequence

AGR-2244 variant position

---

package-lock.json
package.json
src/containers/genePage/genomeFeatureWrapper.js
src/lib/genomeFeatureTypes.js

please review, just bumps the version of the GFC

fixes 2241, 2243, and 2239

---

package-lock.json
package.json
src/containers/allelePage/AlleleSequenceView.js

fixes https://agr-jira.atlassian.net/browse/AGR-2242

Fix agr 2242

---

package-lock.json
package.json
src/components/geneOntologyRibbon/index.js

This must be merged after: https://github.com/alliance-genome/agr_ui/pull/686
Add the focus gene if missing after clicking show only experimental annotations.

Fix AGR-2000 (MERGE SECOND)

---

src/containers/allelePage/VariantToTranscriptTable.js

Does NOT fix: AGR-2285. But is related, and will help avoid problem when API is fixed.
Avoid redundant data fetching step, as data fetching is already done by the table.

AGR-2285 data fetching

---

src/containers/allelePage/VariantEffectDetails.js

My fault, but surprised that the linter didn't pick this one up.

AGR-2284 fixed variant location in link

---

src/constants.js
src/containers/allelePage/AlleleSequenceView.js
src/containers/genePage/VariantsSequenceViewer.js
src/containers/genePage/genomeFeatureWrapper.js
src/containers/genePage/index.js

FYI, added hooks to get SARS features in there. 
Note @scottcain  the lookup word into jbrowse (and subsequenly, hopefully apollo) I have is: `SARS-CoV-2`, but let me know if it changes.

added hooks for SARS

---

src/constants.js
src/containers/search/resultsList.js
src/lib/searchHelpers.js
src/reducers/searchParsers.js

A rough draft implementation so that variant & search teams can get a look to fine tune the details

AGR-2303 Initial support for combining allele & variant categories

---

src/constants.js
src/containers/genePage/genomeFeatureWrapper.js

FYI @scottcain  note https://github.com/alliance-genome/agr_jbrowse_config/commit/03d4fb630cdb010367cd0ecbd0e64b8d93f1ded8.

changed the track name

---

src/containers/genePage/genomeFeatureWrapper.js

fixes https://agr-jira.atlassian.net/browse/AGR-2360
its a bit of a hack

fixes AGR-2360

---

src/containers/genePage/genomeFeatureWrapper.js

fixes: https://agr-jira.atlassian.net/browse/AGRHELP-77

updated UI to fix AGRHELP-77

---

src/components/variant/VariantJBrowseLink.js
src/containers/allelePage/AlleleMolecularConsequences.js
src/containers/allelePage/AlleleToVariantTable.js
src/containers/allelePage/VariantEffectDetails.js
src/containers/genePage/alleleTable.js

Added category, hasPhenotype, hasDisease
TODO

AGR-2301 Alleles table on Gene Page

---

src/containers/homepage/MembersSection.js

AGR-2404 Fix FlyBase capitalization

---

src/components/dataTable/index.js
src/containers/allelePage/AlleleMolecularConsequences.js
src/containers/allelePage/AllelePage.js
src/containers/allelePage/AlleleSummary.js
src/containers/allelePage/VariantSummry.js
src/containers/allelePage/VariantToTranscriptTable.js

I highlighted incomplete section to start testing earlier, with agreement from Variant WG.
- attribute list style "Genomic Variant info" section
- remove table style of the same section
- anchor link to sequence section
TODO
[  ] add additional attributes once data is available
[  ] work with Paul on"Highlight in browser"
[  ] "All alleles with this variant"

AGR-2302 allele page

---

Dockerfile

This feels a little clunky, but with only a few commands to run I guess it's fine

Source nvm before running npm commands

---

src/containers/genePage/TransgenicAlleleTable.js
src/containers/genePage/alleleTable.js

- Remove synonym column
- Fix overflowing in construct name column
- Adjust spacing of final rotated column headers to keep them fully visible at widest viewport

AGR-2387 AGR-2403 Transgenic allele table bug fixing

---

src/containers/allelePage/VariantSummry.js

@paaatrick I had to import ExternalLink, which you are rename in your draft. If you don't mind renaming this one in VariantSummry.js, it would be nice.

AGR-2302 allele page: notes, publications, and crossReferences

---

src/containers/genePage/genomeFeatureWrapper.js

Gotta do this the React way, not the OOP way!

AGR-2420 Generate jbrowse link at render time

---

package-lock.json
src/components/geneOntologyRibbon/index.js

Make it clearer that the filter will not show only experimental annotations, but will show only functions/terms supported by at least one experimental annotation. Hence other annotations can be present:
https://agr-jira.atlassian.net/jira/software/c/projects/AGR/issues/AGR-2401?filter=myopenissues

AGR-2401 : fix label

---

src/containers/allelePage/VariantSummry.js

To be added back for 4.0 after download API change to include additional data

AGR-2302 hide variant download button for 3.2

---

src/_theme.scss
src/constants.js
src/containers/search/detailList.js
src/containers/search/resultsList.js
src/containers/search/style.scss
src/lib/searchHelpers.js
src/reducers/searchParsers.js

Category renamed, data provider note added, color set, ID collection in place of Source + Cross References

AGR-1846 Dataset search updates

---

src/containers/allelePage/Sequence.js
src/containers/allelePage/VariantSummry.js

In variant summary, render popup for long nucleotide change (>300 bases)

AGR-2452 long sequence in attribute list

---

src/containers/genePage/genomeFeatureWrapper.js

fixed for AGR-2471

---

src/containers/layout/searchBar/index.js

Release 3.2.0 into Master

---

src/components/dataPage/dataPage.js
src/components/dataTable/DataTable.js
src/components/dataTable/VEPTextCell.js
src/components/dataTable/index.js
src/containers/GeneAlleleDetailsPage/GeneAlleleDetailsTable.js
src/containers/GeneAlleleDetailsPage/index.js
src/containers/genePage/VariantsSequenceViewer.js
src/containers/genePage/alleleTable.js
src/containers/genePage/index.js
src/hooks/useDataTableQuery.js
src/lib/utils.js
src/routes.js

This is still waiting on some API changes. The UI code should be close to its ready state. It would be nice to get reviews from you.
@paaatrick two noteworthy changes, 1) adding the Allele Details page 2) making the table component automatically derive distinct filter values from supplementalData.
@nathandunn @pjhale I moved some logic out of `VariantsSequenceViewer` to its parent components, in order to reuse this component on the new Variant details page. The logic that got moved out involves, 1) calculate fmin, fmax 2) hide viewer while loading 3) display message if no variant is mapped.
If there is anything you are concerned about, please let me know.

(WIP) AGR-2535 allele details page and Feature Viewer

---

src/lib/genomeFeatureTypes.js

Part of fix:
https://agr-jira.atlassian.net/browse/AGR-2176#add-comment?atlOrigin=eyJpIjoiZGQ2YjEwNDQ0NTllNDcyNWExZTA4ZWU0NWZkMTQ5NWQiLCJwIjoiaiJ9

added additional types

---

Makefile

Makefile and Dockerfile updates done to move away from dockerhub and into ECR as our docker image registry. Analogous to alliance-genome/agr_ansible_devops#15

AGR-2528 UI gocd dockerhub => ECR code-changes

---

Dockerfile
Makefile

Please review and approve (once fit), but do not merge yet (I will do so after approval, once I updated the necessary GoCD pipelines, one pipeline at a time).

AGR-2590 UI

---

src/components/interaction/GeneGeneticInteractionDetailTable.js

I assumed the column filter is called `filter.phenotypes`.

AGR-1863 add rendering for the phenotypes column

---

src/lib/searchHelpers.js

Added category to the list of params to be ignored for possible exclusion.

AGR-2124 fix for allele exclusion bug

---

src/containers/search/filterSelector/singleFilterValue.js

Added check for empty string in SingleFilterValue

AGR-2610 suppressed blank assay term on search sidebar

---

src/components/dataTable/AlleleCell.js
src/containers/GeneAlleleDetailsPage/GeneAlleleDetailsTable.js

@cmpich 
I am also waiting on the:

AGR-2535 allele details sorting and more filters

---

package-lock.json
package.json

Fix https://agr-jira.atlassian.net/browse/AGR-2581
And https://agr-jira.atlassian.net/browse/AGR-2287

Fix AGR-2581 and AGR-2287

---

package-lock.json
package.json

Thanks to @sibyl229 for double checking.

Wrong dependency for the table and wrong URL to fetch dbxref

---

src/components/dataTable/EvidenceCode.js
src/components/dataTable/evidenceCodesCell.js

* multiple DOM nodes using the same ref
* tooltip flickering in and out with imprecise placement of cursor, by placing the tooltip to the side
* inline-block layout for multiple codes

AGR-2633 evidence code

---

src/constants.js
src/lib/searchHelpers.js

Changed source field value to come from primary key instead of _id

Autogenerated index

---

src/hooks/useAllVariants.js

API should be fixed before merging.

fetch only LTP variants for the sequence feature viewer

---

Dockerfile

@oblodgett I separated out the docker related work from the javascript one. Hope this helps.

remove ALLIANCE_RELEASE env var from dockerfile

---

package-lock.json
package.json

Updating browser to correctly assign a position for deletions in all conditions.  All changes were in the GenomeFeatureComponent repository and we are just updating the version here.

AGR-2225 bugfix

---

package-lock.json
package.json

Fixing a bug where deletions showed up on the wrong side of the browser.  No UI changes.

AGR-3063 Browser update to fix deletions

---

src/components/pathway/pathwayWidget.js

Pathway section currently has 3 tabs (pathway, reaction, GO-CAMs).
The requirement was to switch to the first tab with data (eg if no pathway, switch to GO-CAMs tab)

AGR-2708: switch to first tab with data

---

package-lock.json
package.json

Small update of the GO-CAM widget. Essentially more docs, wider nodes to fit larger texts.

AGR-2708 cosmetics

---

src/containers/GeneAlleleDetailsPage/GeneAlleleDetailsTable.js
src/hooks/useDataTableQuery.js
src/lib/fetchData.js

- Allow fetch timeout to be overridden and specified per fetch request
- Add message warning about potential long wait time.

AGR-3081 Increase fetch timeout for allele/variants details endpoints

---

src/containers/genePage/alleleTable.js

AGR-3081 change wording and layout for disabled details page link

---

src/components/CovidInfoLink.js

Removed the Covid link information from the attention box and added a link to a NIH survey.

added NIH community call instead of Covid info

---

apps/main-app/src/containers/modLanding/MainSGD.js
apps/main-app/src/containers/modLanding/index.js
apps/main-app/src/containers/modLanding/sgd/About.js
apps/main-app/src/containers/modLanding/wormbase/About.js

Added about page for SGD, link to WB from its about section
SCRUM 616 and 659, maybe even more

SCRUM-616 and SCRUM-659 (add link to WB)

---

apps/main-app/src/constants.js
apps/main-app/src/containers/layout/SiteMap.js
apps/main-app/src/containers/layout/style.scss
apps/main-app/src/containers/modLanding/sgd/Main.js
apps/main-app/src/containers/modLanding/style.scss
apps/main-app/src/containers/modLanding/wb/Main.js

fixed members link
fixed media icons on footer
SGD log in front for decision
refactor scss for MOD landing
fixed title/logo bar size and padding

First sprint sprint

---

apps/main-app/src/constants.js
apps/main-app/src/containers/layout/SiteMap.js
apps/main-app/src/containers/modLanding/content.js
apps/main-app/src/containers/modLanding/style.scss

- using long names for dropdown menu without short names (e.g., 'Zebrafish Information Network' instead of 'Zebrafish Information Network / ZFIN')
- Added content for all other MODs
- Added styles for title bar (needs to be revised depending on header images)

Branding for all other MODs

---

apps/main-app/src/containers/modLanding/content.js
apps/main-app/src/containers/modLanding/style.scss

FB banner added

---

apps/main-app/src/containers/search/search.js

should be fetchData(searchUrl, undefined, 60000) to force default value

fix scrum-206 timeout

---

apps/main-app/src/constants.js

minimal change, merge if OK, otherwise delete branch

Changed GO to GOC on footer for consistency with main page logos

---

apps/main-app/src/constants.js
apps/main-app/src/containers/modLanding/content.js

It is GOC everywhere now

---

apps/main-app/src/containers/modLanding/style.scss

reverted banner to previous stage

---

apps/main-app/src/containers/modLanding/content.js

Updated to what is in the GDoc.

GOC about updated

---

apps/main-app/src/containers/modLanding/wordpressNews.js

Scrum 618 news fix key

---

apps/main-app/src/containers/modLanding/content.js

added ParaSite to WB resources

---

apps/main-app/src/containers/modLanding/About.js

OK. Changes work locally, and only one file is being changed.

Add back MOD abbr to browser tab title

---

apps/main-app/src/containers/modLanding/tests/wb.test.js

Start of tests for worm base landing page.

start of tests

---

apps/main-app/src/constants.js
apps/main-app/src/containers/modLanding/About.js
apps/main-app/src/containers/modLanding/Main.js
apps/main-app/src/containers/modLanding/content.js

Also moving browser tab tags to Main.js from About.js.

SCRUM-976: Use FlyBase and WormBase in place of FB and WB

---

apps/main-app/src/constants.js
apps/main-app/src/containers/homepage/MembersSection.js
apps/main-app/src/containers/modLanding/content.js
apps/main-app/src/containers/modLanding/style.scss
apps/main-app/src/containers/modLanding/tests/wb.test.js
libs/shared-assets/src/lib/organizations.js

More catches of incorrect MOD references. Changes to FlyBase and WormBase URLs and MGD title, per suggestions from @azurebrd. Thanks! Hopefully that's the last of them.

SCRUM-976, SCRUM-977

---

apps/main-app/src/containers/modLanding/About.js
apps/main-app/src/containers/modLanding/Main.js
apps/main-app/src/containers/modLanding/content.js

Use "MGI" in the "Visit" button; updated Resources list (from David Shaw).

MGD tweaks

---

apps/main-app/src/containers/modLanding/Main.js
apps/main-app/src/containers/modLanding/content.js

sorry, keep forget NOT to merge into main branch. static news link for flybase, zfin, goc here.

scrum-995 add static link for flybase, zfin, goc'

---

apps/main-app/src/containers/modLanding/FooterAlt.js
apps/main-app/src/containers/modLanding/Main.js
apps/main-app/src/containers/modLanding/content.js
apps/main-app/src/containers/modLanding/style.scss

Adding early as it is my first venture into react etc. WormBase done so just need to add other members, but you can look at this and decide on any style changes etc that may be wanted. Just giving people advance warning.

footer initial template and data for WormBase

---

apps/main-app/src/containers/modLanding/content.js
apps/main-app/src/containers/modLanding/style.scss
apps/main-app/src/containers/modLanding/tests/wb.test.js

Not ideal , needs different link colours and some text replaced with icons but I am happy for this as a MVP. Feel free to change what ever you like.

added footer data for all

---

apps/main-app/src/containers/modLanding/FooterAlt.js
apps/main-app/src/containers/modLanding/Main.js
apps/main-app/src/containers/modLanding/style.scss

Couple of commits, changes are explained on the commit message

Some changes

---

apps/main-app/src/containers/modLanding/content.js

add news link of MGD

---

apps/main-app/src/containers/downloadsPage/index.js

I have not worked on this repo for a long time so I would have to put a bunch of work into getting an environment setup. I think someone should test it out but I am almost certain that this is the issue and that this will work.

Update VCF assembly for mouse to 39 from 38

---

apps/main-app/src/containers/modLanding/News.js
apps/main-app/src/containers/modLanding/NewsZfin.js
apps/main-app/src/containers/modLanding/content.js

This adds the ZFIN news API, but not sure we want this for the sprint review tomorrow.  I've asked @cerivs , but making the PR to avoid losing track of this.

News zfin (Do NOT Merge)

---

apps/main-app/src/containers/modLanding/Title.js
apps/main-app/src/containers/modLanding/tests/Title/title.test.js
apps/main-app/src/containers/modLanding/tests/wb.test.js

All members done in the one file. No tests for the banner as such as that is done via styles. Hopefully though this should be obvious on viewing the page if this is broken.

Tests for title

---

apps/main-app/src/containers/allelePage/VariantToTranscriptTable.js

Don't delete the branch here, at least for now

testing a fix for the table column width issue

---

apps/main-app/src/containers/genePage/genomeFeatureWrapper.js
package-lock.json
package.json

This fixes two separate issues.  The chr is now corrected to get the 
correct prefix and the viewer now loads even when a blank variant JSON 
is given.  Updates genomeFeatureComponent version.
There was a bunch of changes to package-lock.json.  The only change I made was to the genomeFeatureComponent version. I'm not sure if those should be in there but I've left them here for now.

Fixing SGD Bugs

---

apps/main-app/src/components/orthology/constants.js
apps/main-app/src/components/orthology/orthologyUserGuide.js

Updated spelling of sonicParanoid to fix missing data.

SCRUM-1219 fix

---

apps/main-app/src/constants.js
libs/app-shell/src/lib/sitemap.js

(used link to human because why not) addresses https://agr-jira.atlassian.net/browse/SCRUM-1057

adding links for JBrowse to footer and site map KANBAN-166

---

apps/main-app/src/constants.js

Needed for links to jbrowse and (probably)  will make apollo and the widget work

adding frogs to the constants along with other species

---

apps/main-app/src/containers/genePage/genomeFeatureWrapper.js

https://agr-jira.atlassian.net/browse/SCRUM-1962

shot in the dark, but this may fix the X. laevis/apollo issue

---

apps/main-app/src/constants.js

Turn off single cell expression atlas links for Xenopus

SCRUM-1963 - Turn off single cell expression atlas links for Xenopus

---

apps/main-app/src/components/orthology/constants.js
apps/main-app/src/components/orthology/orthologyUserGuide.js

Updated algorithm list to accommodate the Xenbase algorithm.

KANBAN-250 Add Xenbase algorithm

---

apps/main-app/src/components/orthology/constants.js
apps/main-app/src/components/orthology/orthologyUserGuide.js

Removing unused algorithms with DIOPT 9 update fixes.

KANBAN-292 Reverting algorithms with DIOPT 9 data fix

---

apps/main-app/src/constants.js
libs/app-shell/src/lib/sitemap.js

hopefully will address https://agr-jira.atlassian.net/browse/KANBAN-318

removed slash and index.html. Maybe this will fix this 🤷‍♂️

---

apps/main-app/src/routes.js

This works locally. We'll see if it does on stage

SCRUM-2783

---

apps/main-app/src/components/dataTable/AnnotatedEntitiesPopupCuration.js
apps/main-app/src/components/dataTable/AssertedGenes.js
apps/main-app/src/components/dataTable/NoteCell.js
apps/main-app/src/components/disease/diseaseAnnotationTable.js

-- asserted genes display symbol instead of curie
-- main row gene is filtered out of asserted genes
-- notes are prefixed with either note or summary depending on type

SCRUM-2394 asserted genes and notes updates

---

apps/main-app/src/components/interaction/genePhysicalInteractionDetailTable.js
apps/main-app/src/components/interaction/interactionUserGuide.js

Reverts alliance-genome/agr_ui#1145

Revert "Add molecular interactions help popup on gene page"

---

apps/main-app/src/components/dataTable/AnnotatedEntitiesPopupCuration.js
apps/main-app/src/components/dataTable/GeneticModifiersCellCuration.js

SCRUM-2833: make gene and allele links internal 

---

apps/main-app/src/components/dataTable/EvidenceCodeCuration.js
apps/main-app/src/components/paralogy/paralogyFilteredTable.js
apps/main-app/src/components/paralogy/paralogyTable.js
apps/main-app/src/components/paralogy/paralogyUserGuide.js
apps/main-app/src/containers/genePage/index.js
apps/main-app/src/hooks/useGeneParalogy.js

SCRUM-2703: add paralogy section

---

apps/main-app/src/components/disease/diseaseAnnotationTable.js
apps/main-app/src/components/disease/diseaseComparisonRibbon.js
apps/main-app/src/components/expression/expressionAnnotationTable.js
apps/main-app/src/components/expression/expressionComparisonRibbon.js
apps/main-app/src/hooks/useComparisonRibbonTableQuery.js

Sorry @markquintontulloch I might have gotten ahead of myself.

Changed to focus taxon id

---

apps/main-app/src/components/alleleTable/alleleTableSectionHelp.js
apps/main-app/src/containers/genePage/alleleTable.js

Add help text: variant and allele symbol columns

KANBAN-328

---

apps/main-app/src/components/interaction/GeneGeneticInteractionDetailTable.js

Add help text for perturbation columns

KANBAN-326

---

apps/main-app/src/containers/genePage/TransgenicAlleleTable.js

Add help text for knock-down targets column

KANBAN-325

---

package.json

This time I think I really fixed the class thing--never worked with reactstrap before :-/

fixing spacing and class issues

---

package.json

improving the look and feel: updated button text per Paul's suggestion and removed the download arrows

bumping seqpanel version

---

apps/main-app/src/components/paralogy/rankHelp.js

Updated rank description.

---

apps/main-app/src/components/paralogy/rankHelp.js

More clarity for the rank help.

Rank update list

---

apps/main-app/src/components/paralogy/rankHelp.js

No other changes in the stage branch!

Updating test with the Paralogy help correction

---

apps/main-app/src/components/dataTable/AnnotatedEntitiesPopupCuration.js
apps/main-app/src/components/disease/diseaseAnnotationTable.js

To be matched with alliance-genome/agr_java_software#1130

Match API and indexer changes to support curation v0.26.0 (SCRUM-3367)

---

apps/main-app/src/containers/allelePage/AlleleToDiseaseTable.js

Reverts alliance-genome/agr_ui#1221 as consolidation is now fixed on agr_java_software

Revert "SCRUM-2393: consolidation of Disease Qualifiers"

---

apps/main-app/src/components/dataTable/AnnotatedEntitiesPopupCuration.js

Per:
https://agr-jira.atlassian.net/browse/SCRUM-2393?focusedCommentId=40496

SCRUM-2393: Removal of columns

---

apps/main-app/src/constants.js

FYI - I turned on prettier ... so it did a bunch of formatting.  It might be hard to discern my changes from the prettier changes. I changed the About menu in two ways: re-order the submenu items and (for this ticket) appended Data Preservation Commitment to the last sub menu.

KANBAN-457: Add 'Data Preservation' to About menu

---

cdk/amplify-stage-stack.ts

adding proxy settings for jbrowse2 so I can start testing code with it.

fair chance I got the proxy settings for jbrowse2 right

---

src/containers/allelePage/AlleleSequenceView.js
src/containers/genePage/genomeFeatureWrapper.js

Reasonably sure this works but need to test in stage environment to make sure.

adding region highlighting for variants linked out to JBrowse

---

src/components/dataTable/AnnotatedEntitiesPopupCuration.js
src/components/dataTable/utils.js
src/containers/diseasePage/DiseaseToAlleleTable.js
src/containers/diseasePage/DiseaseToGeneTable.js

Also fixed errors in displaying gene table

SCRUM-3743 UI work to display disease page associated alleles from persistent store

---

src/components/dataTable/AnnotatedEntitiesPopupCuration.js
src/components/dataTable/utils.js
src/containers/diseasePage/DiseaseToAlleleTable.js
src/containers/diseasePage/DiseaseToGeneTable.js

Reverts alliance-genome/agr_ui#1296

Revert "SCRUM-3743 UI work to display disease page associated alleles from persistent store"

---

src/components/dataTable/AnnotatedEntitiesPopupCuration.js

Forgot to make the change in the table data column in annotation details pop up, this has been now changed

Change in annotation details pop

---

cdk/amplify-production-stack.ts
cdk/amplify-test-stack.ts

Of course, there's no really good way to test this until it actually goes on production, but I'm reasonably sure I got this right.

adding proxy entries for JB2 for test and production

---

cdk/amplify-production-stack.ts
cdk/amplify-stage-stack.ts
cdk/amplify-test-stack.ts

Added textpresso rewrites and redirects

Textpresso rewrites

---

src/components/dataTable/AnnotatedEntitiesPopupCuration.js
src/components/dataTable/GeneticModifiersCellCuration.js
src/components/dataTable/ModelCellCuration.js
src/components/dataTable/getResourceUrl.js
src/components/dataTable/utils.js

SCRUM-4033 update ModelCellCuration to pass in an object to

---

package.json

https://github.com/geneontology/wc-gocam-viz/issues/37
Updated gocam-viz to [1.0.1-beta.2](https://www.npmjs.com/package/@geneontology/wc-gocam-viz/v/1.0.1-beta.2) for legend issue
cc @kltm @dustine32

Update package.json gocam-viz to test

---

package.json

updated gocam-viz to [1.0.1-beta.2](https://www.npmjs.com/package/@geneontology/wc-gocam-viz/v/1.0.1-beta.2) for legened issue
cc @kltm @dustine32

Update package.json gocam-viz

---

package.json

should address https://agr-jira.atlassian.net/browse/KANBAN-620

should address https://agr-jira.atlassian.net/browse/KANBAN-620

---

package.json

should address https://agr-jira.atlassian.net/browse/KANBAN-643

adding react 19 as a valid peer dep

---

package.json

Should address both https://agr-jira.atlassian.net/browse/KANBAN-643 and https://agr-jira.atlassian.net/browse/KANBAN-646

Scain kanban 643 646

---

src/components/dataPage/style.module.scss

Add vert scroll to nav section

KANBAN-383

---

.github/workflows/github-actions-PR-validation.yml
package-lock.json

@tmushayahama @christabone You forgot to update or at least commit the `package-lock.json` file in [PR#1447](https://github.com/alliance-genome/agr_ui/pull/1447). Depending on how you tested these change, that may mean the installed version during testing was the old one all along. If you just forgot to commit the `package-lock.json` file updates then you can just accept and merge this PR, otherwise please test again (locally) and then accept and merge when proven to be functioning as expected.

Gocamviz 1.1.2 package lock sync

---

src/components/disease/diseaseAnnotationTable.js

This reverts commit 2a9d61662bd9b33ae33db42519d35985e2e7975d.

SCRUM-5109 Enable download button for DA on gene page

---

cdk/amplify-production-stack.ts
cdk/amplify-stage-stack.ts
cdk/amplify-test-stack.ts

fix from bigwig urls for jbrowse

---

src/components/dataTable/DataTable.js
src/components/disease/diseaseComparisonRibbon.js
src/containers/allelePage/AllelePage.js

The gene page "jumps" to a different table section when changing filters on the Alleles and Variants Table.

KANBAN-629 gene page jumps to different section

---

.github/workflows/claude-review.yml
README.md

- Uses organization-wide reusable workflow from alliance-genome/.github
- Three-tier review system: <25 lines (skip), 25-300 (Claude), >300 (zen tools)
- Custom focus on UI/UX accessibility and React best practices
- Manual reviews available with @claude comment trigger
- Developer education in every review comment
See https://github.com/alliance-genome/.github for documentation

Add Claude Code automated PR reviews [TEST]

---

.github/workflows/github-actions-PR-validation.yml
.prettierignore
index.html
src/containers/genePage/GeneModelsTable.js

This ticket now needs to be merged.

KANBAN-732 test prettier fails for PR

---

src/components/dataTable/utils.jsx

Added special case for PMCID in getSingleUrl function (resource descriptor)

fix(utils): add PMCID support to reference URL generation
